/* Mission Control interface. Every view is a function that returns a string, so the whole app can be
   rendered and checked under Node before it ships. No framework, no network, nothing to fail to load. */
(function (root, factory) { if (typeof module === "object" && module.exports) module.exports = factory(); else root.MCUI = factory(); })(typeof self !== "undefined" ? self : this, function () {
"use strict";
const VERSION = "v111";
const TABS = [["today", "Today", ""], ["classic", "Classic", "c"], ["draft", "Draft", "d"], ["leagues", "Leagues", ""], ["fixtures", "Fixtures", ""], ["players", "Players", ""], ["odds", "Odds", ""], ["review", "Review", ""], ["lab", "Lab", ""]];
const KIT = { ARS: "#EF0107", AVL: "#670E36", BOU: "#DA291C", BRE: "#E30613", BHA: "#0057B8", CHE: "#034694", COV: "#79BCE7", CRY: "#1B458F", EVE: "#003399", FUL: "#F5F5F5", HUL: "#F5A12D", IPS: "#1C4BA0", LEE: "#FFFFFF", LIV: "#C8102E", MCI: "#6CABDD", MUN: "#DA291C", NEW: "#241F20", NFO: "#DD0000", SUN: "#EB172B", TOT: "#132257" };
const esc = (s) => String(s == null ? "" : s).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
const f1 = (x) => (x == null || isNaN(x) ? "–" : (Math.round(x * 10) / 10).toFixed(1));
const f0 = (x) => (x == null || isNaN(x) ? "–" : String(Math.round(x)));
const pct = (x) => (x == null || isNaN(x) ? "–" : Math.round(x * 100) + "%");
const money = (x) => "£" + (Math.round(x * 10) / 10).toFixed(1) + "m";
const sign = (x) => (x >= 0 ? "+" : "−") + f1(Math.abs(x));
const thousands = (n) => String(Math.round(n)).replace(/\B(?=(\d{3})+(?!\d))/g, ",");
function sast(iso, withDay) { if (!iso) return "–"; try { const d = new Date(iso); const o = { timeZone: "Africa/Johannesburg", hour: "2-digit", minute: "2-digit", hour12: false }; if (withDay !== false) { o.weekday = "short"; o.day = "numeric"; o.month = "short"; } return new Intl.DateTimeFormat("en-GB", o).format(d).replace(",", ""); } catch (e) { return iso; } }
function sastShort(iso) { if (!iso) return "–"; try { return new Intl.DateTimeFormat("en-GB", { timeZone: "Africa/Johannesburg", weekday: "short", hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(iso)).replace(",", ""); } catch (e) { return iso; } }
function countdown(ms) { if (ms <= 0) return "locked"; const m = Math.floor(ms / 60000), d = Math.floor(m / 1440), h = Math.floor((m % 1440) / 60), mm = m % 60; return (d ? d + "d " : "") + (d || h ? h + "h " : "") + mm + "m"; }

function makeUI(M, DATA, PRE, store) {
  PRE = PRE || {}; const G = DATA.gw, next = G.next, inPlay = G.live > G.lastDone ? G.live : null, focus = inPlay || next;
  const state = Object.assign({ tab: "today", explain: false, draftEnd: M.CFG.draftEnd, market: {}, tickMode: "att", tickSpan: 6, q: "", fpos: 0, ffree: false, fsort: "epn", fmax: 40, faPos: 0, xiMode: "saved", oddsFx: null, oH: "", oD: "", oA: "", busy: null, done: {} }, (store && store.load()) || {});
  if (!TABS.some((t) => t[0] === state.tab)) state.tab = "today";
  M.setDraftEnd(state.draftEnd); if (state.market && Object.keys(state.market).length) M.setMarket(state.market);
  const R = {};                                                        // results computed in this session (override the baked ones)
  const dirty = () => state.draftEnd !== M.CFG.draftEndApi || Object.keys(state.market || {}).length > 0;
  const cEnd = M.CFG.classicEnd, dEnd = () => state.draftEnd, CLAIM_RUNS = 1500;
  const P = M.P, ids = (a) => (a || []).map((id) => P[id]).filter(Boolean);

  /* ── shared pieces ── */
  const club = (t) => `<span class="club" style="background:${KIT[t] || "#888"}"></span>`;
  const flag = (p) => p.st === "a" ? "" : `<span class="card ${p.st === "d" ? "y" : "r"}" title="${esc(p.news || "")}"></span>`;
  const fxText = (p, gw) => { const F = M.fx(p.t, gw); return F.length ? F.map((f) => f.o + " (" + f.ha + ")").join(", ") : "no match"; };
  const help = (t) => `<p class="help">${t}</p>`;
  const stat = (k, v, s) => `<div class="stat"><div class="k">${k}</div><div class="v num">${v}</div>${s ? `<div class="s">${s}</div>` : ""}</div>`;
  function chip(p, gw, o) { o = o || {}; const e = o.pts != null ? o.pts : M.ep(p, gw); return `<div class="pchip">${o.arm ? `<span class="arm">${o.arm}</span>` : ""}<div class="nm">${flag(p)}${esc(p.n)}</div><div class="fx">${esc(fxText(p, gw))}</div><div class="ep num">${o.pts != null ? f0(e) : f1(e)}</div></div>`; }
  function pitch(xi, bench, benchGk, gw, o) { o = o || {}; const row = (k) => xi.filter((p) => p.p === k); const arm = (p) => o.cap && p.id === o.cap.id ? "C" : o.vice && p.id === o.vice.id ? "V" : null;
    const rows = [1, 2, 3, 4].map((k) => `<div class="prow">${row(k).map((p) => chip(p, gw, { arm: arm(p) })).join("")}</div>`).join("");
    const b = (benchGk ? [benchGk] : []).concat(bench || []); return `<div class="pitch">${rows}</div>${b.length ? `<div class="bench">${b.map((p) => chip(p, gw)).join("")}</div><p class="small muted" style="margin:4px 2px 0">Bench, in the order substitutes come on. The number on each player is expected points for gameweek ${gw}.</p>` : ""}`; }
  function range3(cls, s, lo, hi) { const a = (x) => Math.max(0, Math.min(100, (x - lo) / (hi - lo) * 100)); return `<div class="range ${cls}"><div class="track"></div><div class="band" style="left:${a(s.p10)}%;width:${Math.max(2, a(s.p90) - a(s.p10))}%"></div><div class="mid" style="left:calc(${a(s.p50)}% - 1px)"></div></div>`; }
  function sparkline(vals, invert) { if (!vals.length) return ""; const w = 300, h = 56, mn = Math.min.apply(null, vals), mx = Math.max.apply(null, vals), sp = mx - mn || 1; const pts = vals.map((v, i) => { const x = vals.length === 1 ? w / 2 : 6 + i * (w - 12) / (vals.length - 1), y = 8 + (invert ? (v - mn) : (mx - v)) / sp * (h - 16); return [x, y]; });
    return `<svg class="spark" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" role="img" aria-label="trend"><polyline fill="none" stroke="currentColor" stroke-width="2.5" points="${pts.map((p) => p[0].toFixed(1) + "," + p[1].toFixed(1)).join(" ")}"/>${pts.map((p) => `<circle cx="${p[0].toFixed(1)}" cy="${p[1].toFixed(1)}" r="3.5" fill="currentColor"/>`).join("")}</svg>`; }

  /* ── numbers each tab needs, baked where possible, recomputed when a setting has changed ── */
  const classicState = M.classicSquad();
  const myRoster = M.draftRoster();
  function classicLocked() { if (!classicState) return null; const g = DATA.classic.gws[DATA.classic.gws.length - 1]; const pk = g.picks.map((k) => Object.assign({ pl: P[k.id] }, k)).filter((k) => k.pl); const xi = pk.filter((k) => k.pos <= 11).map((k) => k.pl), b = pk.filter((k) => k.pos > 11).sort((a, c) => a.pos - c.pos).map((k) => k.pl);
    return { gw: g.gw, xi, bench: b.filter((p) => p.p !== 1), benchGk: b.find((p) => p.p === 1) || null, captain: (pk.find((k) => k.c) || {}).pl, vice: (pk.find((k) => k.v) || {}).pl, tc: g.chip === "3xc", chip: g.chip, tx: g.tx, hit: g.hit }; }
  function classicSim() { if (R.cSim) return R.cSim; if (PRE.classicSim && !dirty()) return PRE.classicSim; const L = classicLocked(); if (!L) return null; const side = L.gw === focus ? L : (() => { const b = M.bestXI(classicState.squad, focus); return { xi: b.xi, bench: b.bench, benchGk: b.benchGk, captain: b.cap, vice: b.vice }; })(); return (R.cSim = Object.assign({ gw: focus, saved: L.gw === focus }, M.summarise(M.simulate(focus, [side], 6000, 11)[0]))); }
  function solved() { return !dirty() && PRE.solver && PRE.solver.plan && PRE.solver.plan.ok ? PRE.solver : null; }
  function pairUp(outs, ins) { const o = outs.map((i) => P[i]).filter(Boolean).sort((a, b) => a.p - b.p || b.pr - a.pr), n = ins.map((i) => P[i]).filter(Boolean).sort((a, b) => a.p - b.p || b.pr - a.pr), res = [];
    [1, 2, 3, 4].forEach((k) => { const a = o.filter((x) => x.p === k), b = n.filter((x) => x.p === k); a.forEach((x, j) => res.push([x, b[j] || null])); }); return res; }
  function moveText(w) { if (w.chip === "wildcard") return `Wildcard: ${w.in.length} changes`; if (!w.in.length) return w.held ? '<span class="muted">hold</span>' : `roll (${w.ftBefore} free)`;
    return pairUp(w.out, w.in).map((pr) => `${esc(pr[0].n)} to ${pr[1] ? esc(pr[1].n) : "?"}`).join(", ") + (w.hits ? ` <span class="bad">(−${4 * w.hits})</span>` : ""); }
  function transfers() { if (R.tr) return R.tr; if (PRE.transfers && !dirty()) return PRE.transfers; return null; }
  function wild() { if (R.wc) return R.wc; if (PRE.wildcard && !dirty()) return PRE.wildcard; return null; }
  function moves() { if (R.mv) return R.mv; if (PRE.draftMoves && !dirty()) return PRE.draftMoves; const all = M.draftMoves(myRoster, next, dEnd()); return (R.mv = { top: packMoves(M.bestDistinctMoves(all, 5, 0.5)), all: packMoves(all.slice(0, 40)) }); }
  function contest() { if (R.ct) return R.ct; if (PRE.contest && !dirty()) { const c = PRE.contest; return (R.ct = { ahead: c.ahead, picks: c.picks, taken: new Set([].concat.apply([], Object.values(c.picks).map((v) => v.map((m) => m.add)))) }); }
    const c = M.contested(next, dEnd(), 3); return (R.ct = { ahead: c.ahead, picks: c.picks, taken: new Set([].concat.apply([], Object.values(c.picks).map((v) => v.map((m) => m.add)))) }); }
  function backups() { if (R.bk) return R.bk; const ct = contest(); if (!ct.taken.size) return (R.bk = []); if (PRE.backups && !dirty()) return (R.bk = PRE.backups);
    const pool = M.waiverPool().filter((p) => !ct.taken.has(p.id)); return (R.bk = packMoves(M.bestDistinctMoves(M.draftMoves(myRoster, next, dEnd(), { pool }), 5, 0.5))); }
  function packMoves(a) { return a.map((m) => ({ add: m.add.id, drop: m.drop.id, how: m.how || M.howToGet(m.add), gain: m.gain, gainNext: m.gainNext })); }
  function waiverPri() { const e = DATA.draft.entries.find((x) => x.name === DATA.draft.me); return e ? e.waiver : null; }
  function oppName(gw) { const m = DATA.draft.matches.find((x) => x.gw === gw && (x.a === DATA.draft.me || x.b === DATA.draft.me)); return m ? (m.a === DATA.draft.me ? m.b : m.a) : null; }
  function sidesFor(gw) { const on = oppName(gw); if (!on) return null; const mineNow = gw === inPlay ? (DATA.draft.rivalsNow[DATA.draft.me] || ((DATA.draft.myGws.find((g) => g.gw === gw) || {}).picks)) : null, theirNow = gw === inPlay ? DATA.draft.rivalsNow[on] : null;
    const me = M.sideFromRoster(myRoster, gw, mineNow), them = M.sideFromRoster(M.draftRoster(on), gw, theirNow); return me && them ? { on, me, them } : null; }
  function duel() { if (R.duel) return R.duel; if (PRE.h2h && !dirty()) return PRE.h2h; const S = sidesFor(focus); if (!S) return null; const r = M.h2h(focus, S.me, S.them, 8000, 5); return (R.duel = Object.assign({ gw: focus, opp: S.on, mySaved: S.me.saved, theirSaved: S.them.saved }, r)); }
  function race() { if (R.race) return R.race; if (PRE.race && !dirty()) return PRE.race; return (R.race = M.titleRace(next, dEnd(), 4000, 3)); }

  /* ════════════ TODAY ════════════ */
  function vToday() {
    const evNext = G.events.find((e) => e.id === next), wv = (DATA.draft.events[next] || {}).wv, gwFx = DATA.fixtures.filter((f) => f.gw === focus).sort((a, b) => (a.ko || "").localeCompare(b.ko || ""));
    const L = classicLocked(), cXI = L && L.gw === focus ? L.xi : (classicState ? (M.bestXI(classicState.squad, focus) || { xi: [] }).xi : []); const S = sidesFor(focus), dXI = S ? S.me.xi : [];
    const rows = gwFx.map((f) => { const mine = (arr, cls) => arr.filter((p) => p.t === f.h || p.t === f.a).map((p) => `<span class="dot ${cls}">${esc(p.n)}</span>`).join("");
      const sc = f.st || f.fin ? `${f.hs != null ? f.hs : 0}–${f.as != null ? f.as : 0}` : sastShort(f.ko); return `<div class="fxrow"><span class="t">${f.h} v ${f.a}</span><span class="ko">${esc(sc)}</span><span class="mine">${mine(cXI, "c")}${mine(dXI, "d")}</span></div>`; }).join("");
    const board = `<div class="board"><p class="kicker">${inPlay ? `Gameweek ${inPlay} is in play. Gameweek ${next} locks in` : `Gameweek ${next} locks in`}</p><div class="big num" data-countdown="${esc(evNext ? evNext.dl : "")}">${evNext ? countdown(new Date(evNext.dl).getTime() - Date.now()) : "–"}</div>
      <p class="when">${evNext ? sast(evNext.dl) + " SAST" : ""}</p>${clocks()}<div class="fxlist">${rows}</div>
      <p class="small" style="margin:10px 0 0;opacity:.9"><span class="dot c">amber</span> your Classic starters &nbsp; <span class="dot d">blue</span> your Draft starters. Times are South African.</p></div>`;
    return `<section>${board}</section>${checklistHtml()}<section class="two">${todayClassic()}${todayDraft()}</section>${deltaHtml()}${whatsNew()}`;
  }
  function clocks() { const de = DATA.draft.events[next] || {}, items = [["Draft trades close", de.tr], ["Draft waivers settle", de.wv]].filter((x) => x[1] && new Date(x[1]).getTime() > Date.now());
    return items.length ? `<div class="clocks">${items.map((x) => `<div class="clock"><span>${x[0]}</span><b class="num" data-countdown="${esc(x[1])}">${countdown(new Date(x[1]).getTime() - Date.now())}</b><span>${esc(sast(x[1]))}</span></div>`).join("")}</div>` : ""; }
  function checklist() { const evN = G.events.find((e) => e.id === next) || {}, de = DATA.draft.events[next] || {}, S = solved(), CS = claimSheet(), T = (R.trades || (!dirty() && PRE.trades) || []).filter((t) => t.both), items = [];
    const before = (iso, h) => iso ? new Date(new Date(iso).getTime() - h * 3600e3).toISOString() : null;
    if (T.length && de.tr) items.push({ id: "trade", due: de.tr, game: "d", text: `Propose ${esc(P[T[0].get].n)} from ${esc(T[0].rival)} for ${esc(P[T[0].give].n)} (you ${sign(T[0].mine)}, they ${sign(T[0].theirs)})` });
    items.push({ id: "rebuild", due: before(de.wv || evN.dl, 24), game: "", text: "Ask for an update once the international matches are over, so the plan and claims use the latest injuries and prices" });
    if (CS) items.push({ id: "claims", due: de.wv, game: "d", text: `Lodge the ${CS.sheet.length} Draft claims in the order on the Draft tab, first ${esc(P[CS.sheet[0].add].n)} for ${esc(P[CS.sheet[0].drop].n)}` });
    if (S) { const w = S.plan.weeks[0]; items.push({ id: "classic", due: evN.dl, game: "c", text: w.chip === "wildcard" ? `Play the wildcard and build the planned fifteen; captain ${esc(P[w.cap].n)}, vice ${esc(P[w.vice].n)}` : w.in.length ? `Make the planned transfers (${moveText(w)}); captain ${esc(P[w.cap].n)}` : `Roll the free transfer; captain ${esc(P[w.cap].n)}` }); }
    items.push({ id: "draftxi", due: evN.dl, game: "d", text: "Once waivers settle, sign any free agent still worth it and set the Draft eleven from the best-eleven view" });
    return items.filter((x) => x.due).sort((a, b) => a.due.localeCompare(b.due)); }
  function checklistHtml() { const L = checklist(); if (!L.length) return ""; const done = state.done || {}, n = L.filter((x) => done[next + ":" + x.id]).length;
    return `<section><h2>Before gameweek ${next}</h2><p class="lede">${n} of ${L.length} done. Tap an item to tick it off; ticks are kept on this device.</p><div class="panel">${L.map((x) => { const k = next + ":" + x.id, on = !!done[k];
      return `<button class="todo${on ? " on" : ""}" data-act="tick" data-v="${esc(k)}" aria-pressed="${on}"><span class="box">${on ? "✓" : ""}</span><span class="what">${x.game ? `<span class="tag ${x.game}">${x.game === "c" ? "Classic" : "Draft"}</span> ` : ""}${x.text}</span><span class="due">${esc(sast(x.due))}</span></button>`; }).join("")}</div></section>`; }
  function deltaHtml() { const d = DATA.delta; if (!d || !d.since || (!d.prices.length && !d.flags.length)) return "";
    const S = solved(), mine = new Set([].concat(classicState ? classicState.squad.map((p) => p.id) : [], myRoster.map((p) => p.id), S ? S.plan.weeks[0].squad : [], claimSheet() ? claimSheet().sheet.map((e) => e.add) : []));
    const rel = (x) => mine.has(x.id), pr = d.prices.filter(rel), fl = d.flags.filter(rel);
    return `<section><h3>Since the last build (${esc(sast(d.since))})</h3><div class="panel"><p class="small">${d.prices.length} price changes and ${d.flags.length} flag changes across the game. ${pr.length || fl.length ? "Affecting your squads, plan or claims:" : "None affects your squads, plan or claims."}</p>${pr.length || fl.length ? `<ul class="plain">${pr.map((x) => `<li>${club(P[x.id].t)}<b>${esc(P[x.id].n)}</b> ${money(x.from)} to ${money(x.to)}</li>`).join("")}${fl.map((x) => `<li>${club(P[x.id].t)}${flag(P[x.id])}<b>${esc(P[x.id].n)}</b>: ${esc(x.news || "flag cleared")}</li>`).join("")}</ul>` : ""}</div></section>`; }
  function flagged(list) { return list.filter((p) => p.st !== "a").map((p) => `${esc(p.n)} (${p.cop != null ? p.cop + "%" : "out"}${p.ret ? ", back about " + sast(p.ret + "T12:00:00Z").split(" ").slice(1, 3).join(" ") : ""})`); }
  function todayClassic() {
    if (!classicState) return `<div class="panel c"><span class="tag c">Classic</span><p>No Classic picks in the feed yet.</p></div>`;
    const L = classicLocked(), sim = classicSim(), tr = transfers(), wc = wild(), fl = flagged(classicState.squad), steps = [];
    const lastRes = !inPlay ? lastClassic() : null;
    if (lastRes) steps.push(`<b>Gameweek ${lastRes.gw}: ${lastRes.pts} points</b> against an average of ${lastRes.avg}${lastRes.prevRank ? `. Overall rank ${thousands(lastRes.prevRank)} to <b>${thousands(lastRes.rank)}</b> (${lastRes.rank < lastRes.prevRank ? "up" : "down"} ${thousands(Math.abs(lastRes.prevRank - lastRes.rank))})` : ""}. Captain ${esc(lastRes.cap)} ${lastRes.capPts}.${lastRes.moves.length ? " " + lastRes.moves.map((m) => `${esc(m.outN)} to ${esc(m.inN)}: ${m.inPts} against ${m.outPts} (${sign(m.inPts - m.outPts)})`).join("; ") + "." : ""}`);
    if (inPlay && L && L.gw !== inPlay) steps.push(`<b>Gameweek ${inPlay} is locked and its teams publish once the matches start.</b> Shown here is your last published eleven, from gameweek ${L.gw}, which is also your current fifteen: no transfers have been made all season.${sim ? ` On the best eleven from it, expect about <b>${f0(sim.p50)}</b>, usually between ${f0(sim.p10)} and ${f0(sim.p90)}.` : ""}`);
    else if (L && L.gw === inPlay) steps.push(`<b>Gameweek ${L.gw} is locked.</b> Captain ${esc(L.captain ? L.captain.n : "–")}, vice ${esc(L.vice ? L.vice.n : "–")}${L.chip ? ", chip played: " + esc(chipName(L.chip)) : ", no chip"}${L.tx ? ", " + L.tx + " transfer" + (L.tx > 1 ? "s" : "") + (L.hit ? " (−" + L.hit + ")" : "") : ", no transfers"}.${sim ? ` Expect about <b>${f0(sim.p50)}</b>; four weeks in five it lands between ${f0(sim.p10)} and ${f0(sim.p90)}.` : ""}`);
    else if (sim) steps.push(`<b>Gameweek ${focus} forecast:</b> about ${f0(sim.p50)} points, usually between ${f0(sim.p10)} and ${f0(sim.p90)}, on your best eleven.`);
    if (fl.length) steps.push(`<b>Flagged in your fifteen:</b> ${fl.join("; ")}.`);
    const S = solved();
    if (S) { const w = S.plan.weeks[0], nw = (S.timing && S.timing.never && S.timing.never.ok ? S.timing.never : null) || (S.noWildcard && S.noWildcard.ok ? S.noWildcard : null), chips = S.plan.weeks.filter((x) => x.chip && x.chip !== "wildcard").map((x) => `${chipName(x.chip)} in gameweek ${x.gw}${x.chip === "3xc" ? " on " + esc(P[x.cap].n) : ""}`);
      steps.push(`<b>Points plan for gameweek ${w.gw}: ${w.chip === "wildcard" ? "play the wildcard" : w.in.length ? moveText(w) : "roll the free transfer"}, captain ${esc(P[w.cap].n)}.</b> ${chips.length ? "Then " + chips.join(", ") + ". " : ""}The plan is worth ${f0(S.plan.total)} expected points to gameweek ${S.plan.weeks[S.plan.weeks.length - 1].gw}${nw ? `, ${sign(S.plan.total - nw.total)} on the best plan that keeps the wildcard` : ""}. ${freeTransfersLine()}`);
    } else steps.push(freeTransfersLine() + (tr && tr.moves.length ? ` Best first move: <b>${esc(P[tr.moves[0].out].n)} to ${esc(P[tr.moves[0].inn].n)}</b>, worth ${sign(tr.moves[0].gain)} points to gameweek ${cEnd}.` : ""));
    if (!S && wc && tr) { const edge = wc.value - tr.value; steps.push(edge > 8 ? `<b>The wildcard is worth playing.</b> A fresh fifteen beats your squad plus its best free transfers by ${sign(edge)} points to gameweek ${cEnd}, and your ${classicState.ft} banked free transfers survive it. Build it late, after the international matches, before ${sast((G.events.find((e) => e.id === next) || {}).dl)} SAST.` : `<b>Hold the wildcard for now.</b> A fresh fifteen beats free transfers by only ${sign(edge)} points to gameweek ${cEnd}.`); }
    return `<div class="panel c"><span class="tag c">Classic</span><h3 style="margin-top:6px">${esc(DATA.classic.name)}</h3><ol class="steps">${steps.map((s) => `<li>${s}</li>`).join("")}</ol><div class="row"><button class="btn ghost" data-act="tab" data-v="classic">Open Classic</button></div></div>`;
  }
  function lastClassic() { const gws = DATA.classic.gws.filter((g) => g.gw <= G.lastDone); if (!gws.length) return null; const g = gws[gws.length - 1], prev = gws.length > 1 ? gws[gws.length - 2] : null, cap = g.picks.find((k) => k.c);
    const moves = (DATA.classic.transfersLog || []).filter((t) => t.gw === g.gw).map((t) => { const hi = (P[t.in] && P[t.in].h) || {}, ho = (P[t.out] && P[t.out].h) || {}; return { inN: P[t.in] ? P[t.in].n : "?", outN: P[t.out] ? P[t.out].n : "?", inPts: hi[g.gw] ? hi[g.gw][1] : 0, outPts: ho[g.gw] ? ho[g.gw][1] : 0 }; });
    return { gw: g.gw, pts: g.pts, avg: g.avg, rank: g.rank, prevRank: prev ? prev.rank : null, cap: cap && P[cap.id] ? P[cap.id].n : "–", capPts: cap ? (cap.pts || 0) * cap.mult : 0, moves }; }
  function lastDraft() { const m = DATA.draft.matches.filter((x) => x.fin && x.gw <= G.lastDone && (x.a === DATA.draft.me || x.b === DATA.draft.me)).sort((a, b) => b.gw - a.gw)[0]; if (!m) return null; const mine = m.a === DATA.draft.me ? m.ap : m.bp, opp = m.a === DATA.draft.me ? m.bp : m.ap; return { gw: m.gw, mine, opp, on: m.a === DATA.draft.me ? m.b : m.a, res: mine > opp ? "won" : mine < opp ? "lost" : "drew" }; }
  function freeTransfersLine() { return `Free transfers for gameweek ${next}: ${classicState.ft}${classicState.ftSure ? "" : " (assumes none were used this week)"}, bank ${money(classicState.bank)}.`; }
  function todayDraft() {
    const d = duel(), mv = moves(), st = DATA.draft.standings.find((s) => s.name === DATA.draft.me), fl = flagged(myRoster), steps = [], wv = (DATA.draft.events[next] || {}).wv, ld = !inPlay ? lastDraft() : null;
    if (ld) steps.push(`<b>Gameweek ${ld.gw}: you ${ld.res} ${ld.mine}–${ld.opp}</b> against ${esc(ld.on)}.`);
    if (d) steps.push(`<b>${d.gw === inPlay ? "This week" : "Gameweek " + d.gw}: ${esc(d.opp)}.</b> You win ${pct(d.win)} of the time, draw ${pct(d.draw)}. You: about ${f0(d.me.p50)} (${f0(d.me.p10)} to ${f0(d.me.p90)}). Them: about ${f0(d.them.p50)} (${f0(d.them.p10)} to ${f0(d.them.p90)}).`);
    if (st) steps.push(`<b>Table:</b> ${ordinal(st.rank)} of ${DATA.draft.standings.length}, ${st.w} won, ${st.d} drawn, ${st.l} lost. Points scored ${st.pf}, conceded ${st.pa}.`);
    const CSh = claimSheet();
    if (CSh) steps.push(`<b>Claims for gameweek ${next}: ${CSh.sheet.length} to lodge, first ${esc(P[CSh.sheet[0].add].n)} for ${esc(P[CSh.sheet[0].drop].n)}.</b> Expected ${sign(CSh.meanValue - CSh.valueNow)} points to gameweek ${dEnd()} (${sign(CSh.p10 - CSh.valueNow)} to ${sign(CSh.p90 - CSh.valueNow)}), and ${sign(CSh.valueStress - CSh.valueNow)} even if every rival claims the same names.${wv ? " Waivers settle " + sast(wv) + " SAST." : ""} The Draft tab has the ordered sheet with the chance each claim lands.`);
    else if (mv && mv.top.length) { const ct = contest(), clash = mv.top.slice(0, 3).filter((m) => ct.taken.has(m.add)).map((m) => P[m.add].n);
      steps.push(`<b>Best ${DATA.draft.waiversProcessed ? "move" : "claim"} for gameweek ${next}:</b> add ${esc(P[mv.top[0].add].n)}, drop ${esc(P[mv.top[0].drop].n)} (${sign(mv.top[0].gain)} points to gameweek ${dEnd()}).${wv ? " Waivers settle " + sast(wv) + " SAST." : ""}${clash.length && ct.ahead.length ? ` ${esc(ct.ahead.join(", "))} claim${ct.ahead.length > 1 ? "" : "s"} before you and the model has them wanting ${esc(clash.join(", "))} too; the Draft tab lists your backups.` : ""}`); }
    if (fl.length) steps.push(`<b>Flagged on your roster:</b> ${fl.join("; ")}.`);
    return `<div class="panel d"><span class="tag d">Draft</span><h3 style="margin-top:6px">${esc(DATA.draft.me)}, ${esc(DATA.draft.league.name)}</h3><ol class="steps">${steps.map((s) => `<li>${s}</li>`).join("")}</ol><div class="row"><button class="btn ghost" data-act="tab" data-v="draft">Open Draft</button></div></div>`;
  }
  function whatsNew() { const rd = DATA.draft.league.redraft, items = (PRE.changes || []).slice();
    if (rd) items.unshift(`Your Draft league's settings put the next draft on ${sast(rd.at)} SAST, taking effect from gameweek ${rd.fromGw}. That means this roster plays through gameweek ${rd.fromGw - 1}. The Draft tab plans to gameweek ${dEnd()}; change it there if the admin moves the date.`);
    return `<section><h2>What this build knows</h2><p class="lede">Feeds pulled ${sast(DATA.asOf)} SAST. Desk research dated ${sast(DATA.intel.asOf)} SAST. The two games are scored and planned separately everywhere in this app.</p><div class="panel"><ul class="plain">${items.map((x) => `<li>${x}</li>`).join("")}${(DATA.intel.notes || []).map((x) => `<li>${esc(x)}</li>`).join("")}</ul></div></section>`; }
  const ordinal = (n) => n + (n % 10 === 1 && n % 100 !== 11 ? "st" : n % 10 === 2 && n % 100 !== 12 ? "nd" : n % 10 === 3 && n % 100 !== 13 ? "rd" : "th");
  const chipName = (c) => ({ wildcard: "Wildcard", freehit: "Free Hit", bboost: "Bench Boost", "3xc": "Triple Captain" }[c] || c);

  /* ════════════ CLASSIC ════════════ */
  function vClassic() {
    if (!classicState) return `<section><h2>Classic</h2><p class="lede">No Classic picks in the feed yet.</p></section>`;
    const C = DATA.classic, L = classicLocked(), sim = classicSim(), last = C.season[C.season.length - 1] || {}, usedChips = C.chipsUsed.map((c) => c.name + ":" + (c.gw <= 19 ? 1 : 2));
    const left = ["wildcard", "freehit", "bboost", "3xc"].filter((c) => !C.chipsUsed.some((u) => u.name === c && u.gw <= 19));
    const strip = `<div class="strip">${stat("Total points", thousands(C.total), "gameweek " + (last.gw || "–") + ": " + (last.pts != null ? last.pts : "–"))}${stat("Overall rank", thousands(C.rank), "top " + Math.max(1, Math.round(C.rank / C.players * 100)) + "% of " + (C.players / 1e6).toFixed(1) + "m")}${stat("Free transfers", String(classicState.ft), "for gameweek " + next + ", bank " + money(classicState.bank))}${stat("Chips left to gameweek " + cEnd, String(left.length), left.map(chipName).join(", ") || "none")}</div>`;
    const showSaved = state.xiMode === "saved" && L && L.gw === focus, b = M.bestXI(classicState.squad, showSaved ? focus : next), gwShown = showSaved ? focus : next;
    const pitchHtml = showSaved ? pitch(L.xi, L.bench, L.benchGk, gwShown, { cap: L.captain, vice: L.vice }) : pitch(b.xi, b.bench, b.benchGk, gwShown, { cap: b.cap, vice: b.vice });
    const capBoard = classicState.squad.map((p) => ({ p, v: M.ep(p, gwShown) })).sort((a, c) => c.v - a.v).slice(0, 5);
    return `<section><h2>Classic, ${esc(C.name)}</h2><p class="lede">Planned to gameweek ${cEnd}, when the first set of chips expires. Everything here is Classic only.</p>${strip}</section>${planHtml()}
    <section><div class="row" style="justify-content:space-between"><h3 style="margin:0">${showSaved ? "Your locked eleven, gameweek " + focus : "Best eleven from your fifteen, gameweek " + next}</h3>${L && L.gw === focus ? `<div class="seg"><button data-act="xi" data-v="saved" aria-pressed="${showSaved}">Locked</button><button data-act="xi" data-v="best" aria-pressed="${!showSaved}">Next week's best</button></div>` : ""}</div>
      ${help("Expected points are an average over thousands of imagined versions of the match. A player on 6.0 will often score 2 and sometimes 15.")}${pitchHtml}
      ${sim ? `<div class="panel" style="margin-top:12px"><h3>Gameweek ${sim.gw} score forecast</h3><p class="small muted" style="margin:0">${sim.gw !== gwShown ? `This is the week already under way, so nothing can change it; the eleven above is for gameweek ${gwShown}. ` : ""}Middle line is the most likely score. The band covers four weeks in five.</p>${range3("c", sim, 20, 110)}<div class="legend"><span>20</span><span>low ${f0(sim.p10)}, likely <b>${f0(sim.p50)}</b>, high ${f0(sim.p90)}</span><span>110</span></div></div>` : ""}</section>
    <section><h3>Who should wear the armband, gameweek ${gwShown}</h3>${help("The captain's points count double. The best captain is usually the player with the highest expected points, not the most famous one.")}
      <div class="panel scroll"><table><thead><tr><th>Player</th><th>Match</th><th class="n">Expected</th><th class="n">As captain</th><th class="n">Starts</th></tr></thead><tbody>${capBoard.map((x) => { const d = M.parts(x.p, gwShown).det[0]; return `<tr><td>${club(x.p.t)}${flag(x.p)}${esc(x.p.n)}</td><td>${esc(fxText(x.p, gwShown))}</td><td class="n">${f1(x.v)}</td><td class="n"><b>${f1(x.v * 2)}</b></td><td class="n">${d ? pct(d.pStart) : "–"}</td></tr>`; }).join("")}</tbody></table></div></section>
    ${classicTransfersHtml()}${wildcardHtml()}${chipPlanHtml()}`;
  }
  function planHtml() { const S = solved(); if (!S) return PRE.solver && dirty() ? `<section><div class="note flag">The solved points plan was worked out on the built-in settings. You have changed the Draft horizon or added bookmaker prices, so it is hidden until the next rebuild; the quick searches further down still work.</div></section>` : "";
    const pl = S.plan, nw = (S.timing && S.timing.never && S.timing.never.ok ? S.timing.never : null) || (S.noWildcard && S.noWildcard.ok ? S.noWildcard : null), w = pl.weeks[0], fh = (S.freeHit || []).filter((f) => f.free).sort((a, b) => b.gain - a.gain)[0], und = S.undecayed && S.undecayed.ok && (S.undecayed.gap == null || S.undecayed.gap < 0.05) ? S.undecayed : null, T = S.timing;
    const rows = pl.weeks.map((x) => `<tr${x.gw === next ? ' class="me"' : ""}><td>${x.gw}</td><td>${moveText(x)}</td><td>${x.chip && x.chip !== "wildcard" ? chipName(x.chip) : x.chip === "wildcard" ? "Wildcard" : ""}</td><td>${esc(P[x.cap].n)}</td><td class="n">${f1(x.epNet)}</td></tr>`).join("");
    const same = und ? (und.weeks[0].chip === w.chip && und.weeks[0].cap === w.cap) : null;
    return `<section><h3>Points-maximising plan, gameweeks ${w.gw} to ${pl.weeks[pl.weeks.length - 1].gw}</h3>${help("One optimisation decides everything at once: the squad each week, every transfer and whether a four-point hit is worth it, how many free transfers to bank, the eleven, the captain, and the weeks for the wildcard, bench boost and triple captain. It maximises expected points, with later weeks counted slightly less because projections that far out are less certain.")}
      <div class="panel c"><div class="strip" style="margin-top:0">${stat("Expected points", f0(pl.total), "to gameweek " + pl.weeks[pl.weeks.length - 1].gw)}${T && T.later && T.later.ok ? stat("Wildcard later", f0(T.later.total), sign(pl.total - T.later.total) + " for playing it now") : stat("Without the wildcard", nw ? f0(nw.total) : "–", nw ? "the plan is " + sign(pl.total - nw.total) : "")}${stat("Gameweek " + w.gw, w.chip === "wildcard" ? "Wildcard" : w.in.length ? w.in.length + " in" : "Roll", "captain " + esc(P[w.cap].n))}${stat("Free Hit", fh ? "GW" + fh.gw : "–", fh ? sign(fh.gain) + " that week" : "")}</div>
      ${T && T.now && T.later && T.never ? (() => { const tol = Math.round(Math.max(T.now.gap || 0, T.later.gap || 0, T.never.gap || 0) * pl.total);
        /* A solve's gap bounds its own objective, so the most a restricted case could still reach is obj x (1 + gap).
           Comparing the kept plan's objective against that bound is a proof rather than an eyeball: above zero and the
           restriction cannot win however long it is left to run. */
        const bound = (r) => (r && r.obj ? r.obj * (1 + (r.gap || 0)) : 0), proved = (r) => (T.now.obj || 0) > bound(r);
        const lgw = (T.later.weeks.find((x) => x.chip === "wildcard") || {}).gw || "\u2013", edge = T.now.total - T.later.total, clear = edge > tol;
        return `<div class="note ${clear ? "" : "flag"}"><b>Wildcard timing, each case solved on its own to about the same tolerance.</b> Play it in gameweek ${w.gw}: ${f0(T.now.total)}. Play it later, best week gameweek ${lgw}: ${f0(T.later.total)}. Keep it unplayed to gameweek ${cEnd}: ${f0(T.never.total)}. ${proved(T.never) ? `Holding the chip to gameweek ${cEnd} is <b>proved worse</b>: the best plan that never plays it was solved to the end and cannot reach the plan above.` : `Holding the chip is ${f0(T.now.total - T.never.total)} behind, which is still inside the proof tolerance.`} ${clear ? `Gameweek ${w.gw} beats every later week by ${f0(edge)}, more than the tolerance of about ${tol} points, so the week is settled.` : (() => { const tcw = pl.weeks.find((x) => x.chip === "3xc"), days = Math.max(0, Math.round((new Date((G.events.find((e) => e.id === next) || {}).dl).getTime() - Date.now()) / 864e5)), n = w.chip === "wildcard" ? w.in.length : 0;
          const why = [`${days > 6 ? "with " + days + " days to the deadline, you can build after the international matches, once the injury news is in" : "building at the deadline means the injury news is in"}`, `your ${w.ftBefore} free transfer${w.ftBefore === 1 ? "" : "s"} survive the chip and give a second reshuffle in gameweek ${w.gw + 1}`];
          if (tcw) why.push(`the best Triple Captain week, ${esc(P[tcw.cap].n)} (${esc(fxText(P[tcw.cap], tcw.gw))}) in gameweek ${tcw.gw}, needs the new squad in place`);
          if (n >= 6) why.push(`${n} of your fifteen are being replaced anyway, which ${w.ftBefore} free transfers cannot do`);
          return `${proved(T.later) ? `Gameweek ${w.gw} is ahead of every later week in the proof as well, but only just` : `Gameweek ${w.gw} against gameweek ${lgw} is ${f0(edge)}, inside the tolerance of about ${tol} points`}, so treat the two weeks as level on expected points. What tips it to now: ${why.join("; ")}.`; })()}</div>`; })() : ""}
      <h3 style="font-size:1.05rem">Gameweek ${w.gw} under the plan</h3>${pitch(w.xi.map((i) => P[i]), w.bench.map((i) => P[i]), w.gk2 ? P[w.gk2] : null, w.gw, { cap: P[w.cap], vice: P[w.vice] })}
      ${w.chip === "wildcard" ? `<p class="small">Wildcard squad: ${pairUp(w.out, w.in).map((pr) => `${esc(pr[0].n)} out, ${pr[1] ? esc(pr[1].n) : "?"} in`).join("; ")}. Bank after: ${money(w.bank)}.${w.bank < 0.35 ? " The squad is at the budget line: if any target rises before the deadline, one player must give way, so ask for a rebuild in the last two days." : ""} Your ${w.ftBefore} free transfers are kept for gameweek ${w.gw + 1}.</p>` : ""}
      ${priceWatchHtml(w)}${planChart(pl)}
      <div class="scroll" style="margin-top:10px"><table><thead><tr><th>GW</th><th>Moves</th><th>Chip</th><th>Captain</th><th class="n">Expected</th></tr></thead><tbody>${rows}</tbody></table></div>
      <p class="small muted">Transfers are planned week by week for the first ${pl.detail} gameweeks; after that the table holds the squad, because nobody should commit to moves that far out. Hits are allowed but never chosen unless they pay. Players are never sold only to be bought back later. Solved in ${pl.secs}s${pl.gap != null ? ", within " + (pl.gap * 100).toFixed(1) + "% of the best plan that exists" : ""}${und ? `. Counting every week equally instead gives ${f0(und.total)} expected points and ${same ? "the same gameweek " + w.gw + " decision" : "a different gameweek " + w.gw + " decision (" + (und.weeks[0].chip === "wildcard" ? "wildcard" : "no wildcard") + ", captain " + esc(P[und.weeks[0].cap].n) + ")"}` : ""}.</p></div></section>`; }
  function planChart(pl) { const hold = pl.weeks.map((x) => { const b = M.bestXI(classicState.squad, x.gw); return b ? b.tot + b.capV : 0; }), plan = pl.weeks.map((x) => x.epNet);
    const W = 340, H = 150, n = pl.weeks.length, mx = Math.max.apply(null, plan.concat(hold)) * 1.08, bw = (W - 20) / n, y = (v) => H - 18 - (v / mx) * (H - 30);
    const bars = pl.weeks.map((x, i) => { const x0 = 16 + i * bw; return `<rect x="${(x0 + 1).toFixed(1)}" y="${y(hold[i]).toFixed(1)}" width="${(bw / 2 - 1.5).toFixed(1)}" height="${(H - 18 - y(hold[i])).toFixed(1)}" fill="var(--line)"/><rect x="${(x0 + bw / 2).toFixed(1)}" y="${y(plan[i]).toFixed(1)}" width="${(bw / 2 - 1.5).toFixed(1)}" height="${(H - 18 - y(plan[i])).toFixed(1)}" fill="var(--classic)"/>${x.chip ? `<text x="${(x0 + bw / 2).toFixed(1)}" y="${(y(plan[i]) - 3).toFixed(1)}" font-size="8" text-anchor="middle" fill="var(--ink)">${{ wildcard: "WC", bboost: "BB", "3xc": "TC" }[x.chip]}</text>` : ""}<text x="${(x0 + bw / 2).toFixed(1)}" y="${H - 6}" font-size="8" text-anchor="middle" fill="var(--ink2)">${x.gw}</text>`; }).join("");
    const gain = plan.reduce((a, v) => a + v, 0) - hold.reduce((a, v) => a + v, 0);
    return `<h3 style="font-size:1.05rem;margin-top:12px">Week by week: the plan against keeping your fifteen</h3><svg viewBox="0 0 ${W} ${H}" width="100%" role="img" aria-label="Expected points per gameweek, plan against current squad">${bars}</svg><p class="small muted" style="margin:2px 0 0"><span class="card" style="background:var(--line)"></span>keep your fifteen, no transfers, no chips &nbsp; <span class="card" style="background:var(--classic)"></span>the plan. Over the window the plan is worth ${sign(gain)} expected points.</p>`; }
  function priceWatchHtml(w) { const st = M.priceStress(w.squad, w.in, w.out, w.bank, next, cEnd, DATA.classic.sell); if (!st.risers.length && !st.fallers.length && !st.need) return "";
    return `<div class="note ${st.need > 0 ? "flag" : ""}"><b>Price watch.</b> ${st.risers.length ? `Rise pressure on planned buys: ${st.risers.map((i) => esc(P[i].n) + " (" + pct(P[i].press) + " of owners net in)").join(", ")}. ` : ""}${st.fallers.length ? `Fall pressure on planned sales: ${st.fallers.map((i) => esc(P[i].n)).join(", ")}. ` : ""}${st.need > 0 ? (st.fix ? `If those prices move £0.1m before the deadline you are ${money(st.need)} short; the cheapest fix is ${esc(P[st.fix.out].n)} to ${esc(P[st.fix.inn].n)}, costing ${f1(st.fix.loss)} expected points to gameweek ${cEnd}.` : `If those prices move £0.1m before the deadline you are ${money(st.need)} short.`) : "The bank covers a £0.1m move on each of them."} Pressure is net transfers since the last deadline as a share of current owners.</div>`; }
  function classicTransfersHtml() { const tr = transfers(); const body = !tr ? `<p class="muted">Press the button to search every legal move. It takes a few seconds.</p>` : tr.moves.length ? tr.moves.map((m, i) => { const o = P[m.out], n = P[m.inn]; return `<div class="swap"><div class="who"><span class="muted small">Sell</span><br>${club(o.t)}${flag(o)}<b>${esc(o.n)}</b> <span class="muted">${money(sellOf(o))}</span></div><div class="arrow">to</div><div class="who"><span class="muted small">Buy</span><br>${club(n.t)}${flag(n)}<b>${esc(n.n)}</b> <span class="muted">${money(n.pr)}</span></div><div class="gain">Move ${i + 1}: ${sign(m.gain)} points to gameweek ${cEnd}, ${sign(m.gainNext)} in gameweek ${next}. Bank after: ${money(m.bankAfter)}. Next: ${esc(fxRun(n, next, 4))}.</div></div>`; }).join("") + `<p class="small muted">With these ${tr.moves.length} moves your squad is worth ${f0(tr.value)} expected points to gameweek ${cEnd}, captain included.</p>` : `<p>No single move gains more than three quarters of a point across the horizon. Keep the transfers.</p>`;
    return `<section><h3>Best use of your free transfers</h3>${help("A free transfer swaps one player for another at no cost. You have " + classicState.ft + " saved; five is the most you can hold. Each move is tested on the whole run to gameweek " + cEnd + ", not just next week.")}<div class="panel c">${body}<div class="row"><button class="btn" data-act="run" data-v="tr" ${state.busy ? "disabled" : ""}>${state.busy === "tr" ? "Searching…" : tr ? "Search again" : "Find the best moves"}</button></div><p class="small muted">Selling prices are worked out from each player's start price or what you paid, plus half of any rise: the same rule the game uses. They match your ${sast(DATA.screen.at)} SAST Transfers screen to the tenth.</p></div></section>`; }
  const sellOf = (p) => { const s = classicState.squad.find((x) => x.id === p.id); return s ? s.sell : p.pr; };
  const fxRun = (p, g0, n) => { const out = []; for (let g = g0; g < g0 + n; g++) out.push(fxText(p, g)); return out.join(", "); };
  function wildcardHtml() { const wc = wild(), tr = transfers(); let body;
    if (!wc) body = `<p class="muted">Build the best fifteen your budget allows for gameweeks ${next} to ${cEnd}. It takes several seconds on a phone.</p>`;
    else { const sq = ids(wc.squad), b = M.bestXI(sq, next), edge = tr ? wc.value - tr.value : null;
      body = `<p><b>${money(wc.cost)} of ${money(wc.budget)}.</b> Worth ${f0(wc.value)} expected points to gameweek ${cEnd}${edge != null ? `, which is <b>${sign(edge)}</b> against keeping your squad and spending the free transfers` : ""}.</p>${pitch(b.xi, b.bench, b.benchGk, next, { cap: b.cap, vice: b.vice })}
      <div class="note ${edge != null && edge > 8 ? "flag" : ""}">${edge == null ? "" : edge > 8 ? `The gap is big enough to act on. Playing it during the break costs nothing extra: you can keep changing the squad until ${sast((G.events.find((e) => e.id === next) || {}).dl)} SAST, your ${classicState.ft} banked free transfer${classicState.ft === 1 ? " is" : "s are"} kept for gameweek ${next + 1}, and the chip must be used by gameweek ${cEnd} anyway. Build it in the last days before the deadline, once international-duty injuries are known.` : `The gap is small. Free transfers get you most of the way; keep the wildcard for an injury crisis or a fixture swing before gameweek ${cEnd}.`}</div>`; }
    return `<section><h3>Wildcard squad</h3>${help("A wildcard lets you change the whole squad for free, once before gameweek " + cEnd + ". Your first one disappears at the gameweek " + cEnd + " deadline if unused.")}<div class="panel c">${body}<div class="row"><button class="btn" data-act="run" data-v="wc" ${state.busy ? "disabled" : ""}>${state.busy === "wc" ? "Building…" : wc ? "Rebuild" : "Build the wildcard squad"}</button></div></div></section>`; }
  function chipPlanHtml() { const rows = []; for (let g = next; g <= cEnd; g++) { const b = M.bestXI(classicState.squad, g); if (!b) continue; rows.push({ g, tc: b.capV, cap: b.cap, bb: b.bench.concat(b.benchGk ? [b.benchGk] : []).reduce((s, p) => s + M.ep(p, g), 0) }); }
    const tcBest = rows.slice().sort((a, b) => b.tc - a.tc)[0], bbBest = rows.slice().sort((a, b) => b.bb - a.bb)[0];
    return `<section><h3>Triple Captain and Bench Boost</h3>${help("Triple Captain makes one captain score three times instead of twice. Bench Boost counts your four substitutes for one week. Both expire at the gameweek " + cEnd + " deadline.")}<div class="panel scroll"><table><thead><tr><th>Gameweek</th><th>Best captain</th><th class="n">Triple Captain adds</th><th class="n">Bench Boost adds</th></tr></thead><tbody>${rows.map((r) => `<tr${tcBest && r.g === tcBest.g ? ' class="me"' : ""}><td>${r.g}</td><td>${esc(r.cap.n)} ${esc(fxText(r.cap, r.g))}</td><td class="n">${f1(r.tc)}</td><td class="n">${bbBest && r.g === bbBest.g ? "<b>" + f1(r.bb) + "</b>" : f1(r.bb)}</td></tr>`).join("")}</tbody></table>
      <p class="small muted">On today's squad the best Triple Captain week is gameweek ${tcBest ? tcBest.g : "–"} and the best Bench Boost week is gameweek ${bbBest ? bbBest.g : "–"}. A wildcard built with a playing bench lifts the Bench Boost column; re-check after it.</p></div></section>`; }

  /* ════════════ DRAFT ════════════ */
  function vDraft() {
    const Dd = DATA.draft, st = Dd.standings.find((s) => s.name === Dd.me) || {}, d = duel(), S = sidesFor(focus), wv = (Dd.events[next] || {}).wv, rd = Dd.league.redraft, mv = moves();
    const strip = `<div class="strip">${stat("League position", st.rank ? ordinal(st.rank) : "–", `${st.w || 0} won, ${st.d || 0} drawn, ${st.l || 0} lost`)}${stat("Points scored", f0(st.pf), "conceded " + f0(st.pa))}${stat(inPlay ? "This week" : "Next opponent", esc(oppName(focus) || "–"), d ? "you win " + pct(d.win) : "")}${stat("Waivers settle", wv ? sast(wv) : "–", "gameweek " + next + ", SAST")}</div>`;
    /* The horizon and the choices around it follow the league's own draft settings; nothing here is typed. */
    const hz = rd && rd.fromGw ? rd.fromGw - 1 : dEnd(), opts = [hz - 2, hz - 1, hz].filter((g) => g >= 1 && g <= 38);
    const horizon = `<div class="note flag">Planning this roster to <b>gameweek ${dEnd()}</b>. ${rd ? `League settings say the next draft is ${sast(rd.at)} SAST, taking effect from gameweek ${rd.fromGw}, so this roster plays through gameweek ${hz}.` : ""} If the admin brings the draft forward, plan to a shorter horizon: <span class="seg">${opts.map((g) => `<button data-act="dend" data-v="${g}" aria-pressed="${dEnd() === g}">${g}</button>`).join("")}</span></div>`;
    const duelHtml = d && S ? `<div class="panel d"><h3>${esc(Dd.me)} v ${esc(d.opp)}, gameweek ${d.gw}</h3><div class="bar3" role="img" aria-label="win ${pct(d.win)}, draw ${pct(d.draw)}, lose ${pct(d.lose)}"><div class="w" style="flex:${Math.max(0.06, d.win)}">${pct(d.win)} win</div><div class="dr" style="flex:${Math.max(0.06, d.draw)}">${pct(d.draw)}</div><div class="l" style="flex:${Math.max(0.06, d.lose)}">${pct(d.lose)} lose</div></div>
      <p class="small muted" style="margin:0 0 6px">${d.n ? thousands(d.n) : ""} simulated gameweeks. ${S.me.saved ? "Your saved eleven." : "Your best eleven (saved one not public yet)."} ${S.them.saved ? "Their saved eleven." : "Their best eleven from the roster; their real pick may differ."}</p>
      <div class="small">You</div>${range3("d", d.me, 10, 100)}<div class="small">${esc(d.opp)}</div>${range3("o", d.them, 10, 100)}<div class="legend"><span>10</span><span>you ${f0(d.me.p10)} to ${f0(d.me.p90)}, them ${f0(d.them.p10)} to ${f0(d.them.p90)}</span><span>100</span></div>
      <div class="two" style="margin-top:10px">${sideTable("You", S.me.xi, focus)}${sideTable(d.opp, S.them.xi, focus)}</div></div>` : `<div class="panel d"><p>No fixture found for gameweek ${focus}.</p></div>`;
    const b = M.bestXI(myRoster, next);
    const top = mv.top.length ? mv.top.map((m, i) => { const a = P[m.add], x = P[m.drop], how = m.how || M.howToGet(a); return `<div class="swap"><div class="who"><span class="muted small">Add, ${how === "waiver" ? "by waiver claim" : "sign now"}</span><br>${club(a.t)}${flag(a)}<b>${esc(a.n)}</b> <span class="muted">${M.POS[a.p]}, ${a.pts} pts</span></div><div class="arrow">for</div><div class="who"><span class="muted small">Drop</span><br>${club(x.t)}${flag(x)}<b>${esc(x.n)}</b> <span class="muted">${M.POS[x.p]}, ${x.pts} pts</span></div><div class="gain">Claim ${i + 1}: ${sign(m.gain)} points to gameweek ${dEnd()}, ${sign(m.gainNext)} in gameweek ${next}. ${esc(a.n)} next: ${esc(fxRun(a, next, 4))}.${how === "waiver" && DATA.draft.waiversProcessed ? " Dropped this week, so he is locked until the next waiver run." : ""}</div></div>`; }).join("") : `<p>Nothing claimable improves your roster by half a point across the horizon.</p>`;
    const fa = M.waiverPool().filter((p) => !state.faPos || p.p === state.faPos).map((p) => ({ p, n: M.ep(p, next), h: M.epRange(p, next, dEnd()) })).sort((a, c) => c.h - a.h).slice(0, 25), locked = M.lockedFreeAgents().sort((a, c) => c.pts - a.pts).slice(0, 10);
    return `<section><h2>Draft, ${esc(Dd.me)}</h2><p class="lede">${esc(Dd.league.name)}, head-to-head. Everything here is Draft only; no Classic number is ever mixed in.</p>${strip}${horizon}</section>
    <section>${help("Head-to-head means only one thing matters each week: outscoring the one manager you face. The bars show how often you do, across thousands of imagined gameweeks.")}${duelHtml}</section>
    <section><h3>Your best eleven, gameweek ${next}</h3>${b ? pitch(b.xi, b.bench, b.benchGk, next) : ""}</section>
    ${draftPlanHtml()}${claimSheetHtml()}
    <section><h3>${claimSheet() ? "Quick check: single claims by value" : "Waiver claims worth making"}</h3>${help("Until the waiver deadline, claims are processed in priority order, worst team first. After it, unclaimed players are free to sign instantly until the gameweek locks.")}<div class="panel d">${claimPhase()}${top}${claimSheet() ? "" : contestHtml()}</div></section>
    <section><h3>Free agents</h3><div class="row"><div class="seg">${[[0, "All"], [1, "GKP"], [2, "DEF"], [3, "MID"], [4, "FWD"]].map((x) => `<button data-act="fapos" data-v="${x[0]}" aria-pressed="${state.faPos === x[0]}">${x[1]}</button>`).join("")}</div></div>
      <div class="panel scroll"><table><thead><tr><th>Player</th><th>Pos</th><th class="n">Points</th><th class="n">Gameweek ${next}</th><th class="n">To gameweek ${dEnd()}</th><th>How to get him</th><th>Next matches</th></tr></thead><tbody>${fa.map((x) => `<tr><td>${club(x.p.t)}${flag(x.p)}${esc(x.p.n)}</td><td>${M.POS[x.p.p]}</td><td class="n">${x.p.pts}</td><td class="n">${f1(x.n)}</td><td class="n"><b>${f0(x.h)}</b></td><td class="small">${M.howToGet(x.p) === "waiver" ? (DATA.draft.waiversProcessed ? "locked until next waivers" : "waiver claim") : '<span class="good">sign now</span>'}</td><td class="small">${esc(fxRun(x.p, next, 3))}</td></tr>`).join("")}</tbody></table>
      ${locked.length ? `<p class="small muted">Dropped this week, so they must be claimed on waivers rather than signed: ${locked.map((p) => esc(p.n) + " (" + p.t + ", " + p.pts + ")").join(", ")}. Claims are settled worst team first; you are ${waiverPri() ? ordinal(waiverPri()) : "–"} in the order.</p>` : ""}</div></section>
    <section><h3>Trades that help both sides</h3>${help("A rival only accepts a trade that improves their team too. These swaps raise both rosters' expected points, so they have a real chance of being accepted.")}<div class="panel d">${tradesHtml()}<div class="row"><button class="btn" data-act="run" data-v="trade" ${state.busy ? "disabled" : ""}>${state.busy === "trade" ? "Searching…" : R.trades || PRE.trades ? "Search again" : "Find trades"}</button></div></div></section>
    <section><h3>Your roster</h3><div class="panel scroll"><table><thead><tr><th>Player</th><th>Pos</th><th class="n">Points</th><th class="n">Gameweek ${next}</th><th class="n">To gameweek ${dEnd()}</th><th class="n">Starts</th><th>Next matches</th></tr></thead><tbody>${myRoster.slice().sort((a, c) => a.p - c.p || M.epRange(c, next, dEnd()) - M.epRange(a, next, dEnd())).map((p) => `<tr><td>${club(p.t)}${flag(p)}${esc(p.n)}</td><td>${M.POS[p.p]}</td><td class="n">${p.pts}</td><td class="n">${f1(M.ep(p, next))}</td><td class="n"><b>${f0(M.epRange(p, next, dEnd()))}</b></td><td class="n">${pct(M.rateOf(p).pStart)}</td><td class="small">${esc(fxRun(p, next, 3))}</td></tr>`).join("")}</tbody></table></div></section>`;
  }
  function claimSheet() { if (R.cs) return R.cs; if (PRE.claims && !dirty()) return (R.cs = PRE.claims); const S = solved(); if (!S || !S.draft || !S.draft.ok) return null; return (R.cs = buildClaimSheet(S.draft.pairs)); }
  function buildClaimSheet(pairs) {
    const RL = M.rivalClaimLists(next, dEnd(), 4), order = M.waiverOrder(), wanted = new Set(); Object.values(RL).forEach((v) => v.forEach((c) => wanted.add(c.add)));
    const val = (id) => M.epRange(P[id], next, dEnd()), prim = pairs.map((q) => ({ add: q.add, drop: q.drop, gain: val(q.add) - val(q.drop) })).sort((a, b) => b.gain - a.gain), primAdds = new Set(prim.map((q) => q.add));
    const usedB = new Set(), backups = [];
    prim.forEach((q) => { const alt = M.waiverPool().filter((p) => p.p === P[q.drop].p && !primAdds.has(p.id) && !wanted.has(p.id) && !usedB.has(p.id)).map((p) => ({ id: p.id, v: val(p.id) })).sort((a, b) => b.v - a.v)[0];
      if (alt && alt.v - val(q.drop) > 3) { backups.push({ add: alt.id, drop: q.drop, gain: alt.v - val(q.drop), of: q.add }); usedB.add(alt.id); } });
    const tag = (kind, list) => list.map((c) => Object.assign({}, c, { kind }));
    const A = tag("first", prim).concat(tag("backup", backups)), B = [];
    prim.forEach((q) => { B.push(Object.assign({ kind: "first" }, q)); const bk = backups.find((x) => x.of === q.add); if (bk) B.push(Object.assign({ kind: "backup" }, bk)); });
    const pilot = M.claimsMC([{ name: "pilot", list: A }], { runs: 600, seed: 11 }).res[0];
    const C = tag("first", prim.slice().sort((x, y) => y.gain * pilot.land[y.add] - x.gain * pilot.land[x.add])).concat(tag("backup", backups));
    const Dd = tag("first", prim.slice().sort((x, y) => pilot.land[y.add] - pilot.land[x.add] || y.gain - x.gain)).concat(tag("backup", backups));
    const mc = M.claimsMC([{ name: "all first choices, then backups", list: A }, { name: "each backup under its first choice", list: B }, { name: "highest expected gain first", list: C }, { name: "likeliest to land first", list: Dd }], { runs: CLAIM_RUNS, seed: 909 });
    const best = mc.res.slice().sort((a, b) => b.mean - a.mean)[0];
    const roster = M.draftRoster().map((p) => p.id), value = (ids) => M.squadValue(ids.map((i) => P[i]), next, dEnd(), false);
    const sim = M.waiverSim(best.list, RL, order), after = roster.slice(); sim.mine.filter((x) => x.ok).forEach((x) => { const k = after.indexOf(x.drop); if (k >= 0) after[k] = x.add; });
    return { sheet: best.list, strategy: best.name, orderings: mc.res.map((r) => ({ name: r.name, mean: r.mean, p10: r.p10, p90: r.p90 })), land: best.land, runs: mc.runs, meanValue: best.mean, p10: best.p10, p90: best.p90,
      sim: sim.mine.map((x) => ({ round: x.round, add: x.add, drop: x.drop, ok: x.ok, why: x.why || null })), landed: sim.mine.filter((x) => x.ok).map((x) => x.add), lost: sim.mine.filter((x) => !x.ok && x.why === "already claimed").map((x) => x.add),
      valueNow: value(roster), valueStress: value(after), valueAll: value(roster.map((i) => { const q = prim.find((z) => z.drop === i); return q ? q.add : i; })), rivals: Object.fromEntries(Object.entries(RL).map(([k, v]) => [k, v.slice(0, 3).map((c) => c.add)])) };
  }
  function claimSheetHtml() { const C = claimSheet(); if (!C) return ""; const wv = (DATA.draft.events[next] || {}).wv, order = M.waiverOrder(), me = order.indexOf(DATA.draft.me) + 1;
    const landedSet = new Set(C.landed), lostSet = new Set(C.lost), worst = (id) => landedSet.has(id) ? '<span class="good">lands</span>' : lostSet.has(id) ? '<span class="bad">taken</span>' : '<span class="muted">not reached</span>';
    const rows = C.sheet.map((e) => `<tr><td>${e.kind === "backup" ? `<span class="small muted">backup for ${esc(P[e.of].n)}</span><br>` : ""}<b>${esc(P[e.add].n)}</b> for ${esc(P[e.drop].n)}</td><td>${M.POS[P[e.add].p]}</td><td class="n">${sign(e.gain)}</td><td class="n"><b>${pct(C.land[e.add])}</b></td><td class="small">${worst(e.add)}</td></tr>`).join("");
    const act = DATA.draft.activity || {}, busy = Object.entries(act).filter(([k]) => k !== DATA.draft.me).sort((a, b) => b[1].claims - a[1].claims).slice(0, 3).map(([k, v]) => `${esc(k)} ${v.claims} claims in ${v.runs} runs`).join(", ");
    return `<section><h3>Claims to lodge, in this order</h3>${help("This league settles waivers in rounds: each round, managers are visited in waiver order and each one's claims are tried in the order lodged until one lands. The chance beside each claim comes from simulating the waiver run " + CLAIM_RUNS.toLocaleString("en-GB") + " times, with each rival active as often as the league log shows and picking from the moves the model rates best for them.")}
      <div class="panel d"><p class="small">You are ${ordinal(me)} of ${order.length} in the order${wv ? "; waivers settle " + sast(wv) + " SAST" : ""}. Four orderings of the same claims were simulated on identical rival behaviour; <b>${esc(C.strategy)}</b> is worth the most.</p>
      <div class="scroll"><table><thead><tr><th>Claim</th><th>Pos</th><th class="n">Gain</th><th class="n">Chance it lands</th><th>Worst case</th></tr></thead><tbody>${rows}</tbody></table></div>
      <div class="strip">${stat("Roster today", f0(C.valueNow), "expected points to GW" + dEnd())}${stat("Expected after claims", f0(C.meanValue), sign(C.meanValue - C.valueNow) + ", " + f0(C.p10) + " to " + f0(C.p90))}${stat("Worst case", f0(C.valueStress), "every rival takes the same names")}${stat("Every first choice", f0(C.valueAll), "the ceiling")}</div>
      <div class="scroll"><table><thead><tr><th>Ordering</th><th class="n">Expected</th><th class="n">Range</th></tr></thead><tbody>${C.orderings.slice().sort((a, b) => b.mean - a.mean).map((o) => `<tr${o.name === C.strategy ? ' class="me"' : ""}><td>${esc(o.name)}</td><td class="n">${f1(o.mean)}</td><td class="n">${f0(o.p10)}–${f0(o.p90)}</td></tr>`).join("")}</tbody></table></div>
      <p class="small muted">Rival activity from the league log: ${busy}. What the model has them wanting most: ${Object.entries(C.rivals).map(([k, v]) => esc(k) + ": " + v.map((id) => esc(P[id].n)).join(", ")).join("; ")}. Anything still unclaimed once waivers settle can be signed instantly until ${sast((G.events.find((e) => e.id === next) || {}).dl)} SAST.</p></div></section>`; }
  function draftPlanHtml() { const S = solved(); if (!S || !S.draft || !S.draft.ok) return ""; const A = S.draft, B = S.draftIfTaken && S.draftIfTaken.ok ? S.draftIfTaken : null;
    const list = (X) => X.pairs.length ? X.pairs.map((q) => `<div class="small" style="padding:4px 0">${club(P[q.add].t)}<b>${esc(P[q.add].n)}</b> for ${esc(P[q.drop].n)} <span class="muted">${M.POS[q.pos]}</span></div>`).join("") : `<p class="small">No change beats your current fifteen.</p>`;
    return `<section><h3>Best roster to gameweek ${A.weeks[A.weeks.length - 1]}, solved</h3>${help("The optimiser picks the best fifteen from your roster plus every claimable player, re-picking your best eleven every gameweek to the re-draft. It maximises Draft points; in head-to-head that is also what raises your chance of winning each week.")}
      <div class="panel d"><p><b>${A.pairs.length} claim${A.pairs.length === 1 ? "" : "s"}, ${sign(A.value - A.base)} points</b> to gameweek ${A.weeks[A.weeks.length - 1]} (${f0(A.base)} to ${f0(A.value)}).</p>${list(A)}
      ${B ? `<p class="small muted" style="margin-top:8px">If ${esc(S.draftAhead || "the team ahead")} take${(S.draftAhead || "").endsWith("s") ? "" : "s"} ${B.excluded.map((i) => esc(P[i].n)).join(", ")} first, the next-best fifteen is worth ${sign(B.value - B.base)}: ${B.pairs.map((q) => esc(P[q.add].n) + " for " + esc(P[q.drop].n)).join(", ")}.</p>` : ""}</div></section>`; }
  function claimPhase() { const wv = (DATA.draft.events[next] || {}).wv, order = M.waiverOrder(), me = order.indexOf(DATA.draft.me) + 1;
    return DATA.draft.waiversProcessed ? `<p class="small">Waivers for gameweek ${next} have settled. Players marked "sign now" can be added instantly until ${sast((G.events.find((e) => e.id === next) || {}).dl)} SAST; anyone dropped since is locked until the next waiver run.</p>`
      : `<p class="small">Every move before ${wv ? sast(wv) : "the waiver deadline"} SAST is a waiver claim. Claims settle in reverse table order: ${order.map((n, i) => (i + 1) + ". " + esc(n)).join(", ")}. You are ${ordinal(me)}. Instant signings open once they settle, until the gameweek ${next} deadline.</p>`; }
  function contestHtml() { const ct = contest(); if (!ct.ahead.length) return `<p class="small muted">You claim first, so nobody can take your first choice.</p>`;
    const lines = ct.ahead.map((nm) => `<li>${esc(nm)} are most likely to go for ${(ct.picks[nm] || []).map((m) => `${esc(P[m.add].n)} (dropping ${esc(P[m.drop].n)})`).join(", ") || "nothing obvious"}.</li>`).join("");
    const bk = backups(); return `<h3 style="font-size:1.05rem;margin-top:12px">Who claims before you</h3><ul class="plain">${lines}</ul>${bk.length ? `<p class="small">If they get there first, your best claims from what is left:</p>` + bk.slice(0, 4).map((m) => `<div class="small" style="padding:4px 0">${club(P[m.add].t)}<b>${esc(P[m.add].n)}</b> for ${esc(P[m.drop].n)}: ${sign(m.gain)} to gameweek ${dEnd()}</div>`).join("") + `<p class="small muted">Order your claims so each contested target has one of these behind it.</p>` : ""}`; }
  function sideTable(title, xi, gw) { return `<div><div class="small muted">${esc(title)}</div><table><tbody>${xi.slice().sort((a, b) => M.ep(b, gw) - M.ep(a, gw)).map((p) => `<tr><td>${club(p.t)}${flag(p)}${esc(p.n)} <span class="muted small">${esc(fxText(p, gw))}</span></td><td class="n">${f1(M.ep(p, gw))}</td></tr>`).join("")}<tr class="me"><td>Expected total</td><td class="n">${f1(M.xiTotal(xi, gw))}</td></tr></tbody></table></div>`; }
  function tradesHtml() { const t = R.trades || (!dirty() && PRE.trades) || null; if (!t) return `<p class="muted">Search every swap with all ${Math.max(0, (DATA.draft.entries || []).length - 1)} rivals, one for one. It takes a few seconds.</p>`; if (!t.length) return `<p>No swap improves your roster by a point without costing the other side more than they would accept.</p>`;
    const both = t.filter((x) => x.both), ask = t.filter((x) => !x.both).slice(0, 3), card = (x, tone) => { const g = P[x.get], v = P[x.give]; return `<div class="swap"><div class="who"><span class="muted small">Get from ${esc(x.rival)}</span><br>${club(g.t)}${flag(g)}<b>${esc(g.n)}</b> <span class="muted">${M.POS[g.p]}</span></div><div class="arrow">for</div><div class="who"><span class="muted small">Give</span><br>${club(v.t)}${flag(v)}<b>${esc(v.n)}</b> <span class="muted">${M.POS[v.p]}</span></div><div class="gain">You ${sign(x.mine)} points to gameweek ${dEnd()}, they ${sign(x.theirs)}.${tone}</div></div>`; };
    return (both.length ? `<h3 style="font-size:1rem">Both sides gain</h3>` + both.slice(0, 4).map((x) => card(x, "Worth proposing as it stands.")).join("") : "") + (ask.length ? `<h3 style="font-size:1rem;margin-top:10px">Worth asking, at a small cost to them</h3>` + ask.map((x) => card(x, "They lose a little on paper, so lead with why it fits their squad, or offer the better fixtures.")).join("") : ""); }
  function findTrades() { const base = M.squadValue(myRoster, next, dEnd(), false), out = [];
    DATA.draft.entries.forEach((e) => { if (e.name === DATA.draft.me) return; const theirs = M.draftRoster(e.name), tb = M.squadValue(theirs, next, dEnd(), false);
      myRoster.forEach((give) => theirs.forEach((get) => { if (give.p !== get.p) return;                      // Draft squads must stay 2-5-5-3, so every swap is position for position
        const mineSq = myRoster.map((x) => x === give ? get : x), theirSq = theirs.map((x) => x === get ? give : x);
        const quick = M.epRange(get, next, dEnd()) - M.epRange(give, next, dEnd()); if (quick < 0.5) return;
        const mine = M.squadValue(mineSq, next, dEnd(), false) - base; if (mine < 1) return;
        const th = M.squadValue(theirSq, next, dEnd(), false) - tb; if (th < -2.5) return;
        out.push({ rival: e.name, get: get.id, give: give.id, mine, theirs: th, both: th > 0.2 }); })); });
    return out.sort((a, b) => (b.both ? 1 : 0) - (a.both ? 1 : 0) || b.mine + b.theirs - (a.mine + a.theirs)); }

  /* ════════════ LEAGUES ════════════ */
  function vLeagues() {
    const Dd = DATA.draft, rc = race(), byName = {}; rc.forEach((r) => { byName[r.name] = r; });
    const tbl = Dd.standings.map((s) => `<tr${s.name === Dd.me ? ' class="me"' : ""}><td class="n">${s.rank}</td><td>${esc(s.name)}</td><td class="n">${s.w}-${s.d}-${s.l}</td><td class="n">${s.pts}</td><td class="n">${s.pf}</td><td class="n">${byName[s.name] ? f1(byName[s.name].strength) : "–"}</td><td class="n">${byName[s.name] ? pct(byName[s.name].first) : "–"}</td><td class="n">${byName[s.name] ? pct(byName[s.name].top3) : "–"}</td></tr>`).join("");
    const myFx = Dd.matches.filter((m) => !m.fin && m.gw <= dEnd() && (m.a === Dd.me || m.b === Dd.me)).map((m) => { const o = m.a === Dd.me ? m.b : m.a; return `<tr><td>${m.gw}</td><td>${esc(o)}</td><td class="n">${byName[o] ? f1(byName[o].strength) : "–"}</td></tr>`; }).join("");
    const meR = byName[Dd.me];
    const C = DATA.classic, weeksTo19 = Math.max(1, cEnd - next + 1), weeksTo38 = Math.max(1, 38 - next + 1), priv = C.leagues.filter((l) => l.type === "x" && l.n).sort((a, b) => a.n - b.n);
    const lg = priv.map((l) => { const gap = l.leader != null && l.mine != null ? l.leader - l.mine : null, nextUp = l.above && l.above.length ? l.above[l.above.length - 1] : null;
      return `<tr><td>${esc(l.name)}</td><td class="n">${l.rank} of ${l.n}</td><td class="n">${l.last && l.last !== l.rank ? (l.last > l.rank ? '<span class="good">up ' + (l.last - l.rank) + "</span>" : '<span class="bad">down ' + (l.rank - l.last) + "</span>") : "level"}</td><td class="n">${gap != null ? gap : "–"}</td><td class="n">${gap != null ? f1(gap / weeksTo19) : "–"}</td><td class="n">${gap != null ? f1(gap / weeksTo38) : "–"}</td><td class="n">${nextUp && l.mine != null ? nextUp.tot - l.mine : "–"}</td></tr>`; }).join("");
    const ranks = C.season.map((s) => s.rank);
    return `<section><h2>Draft table</h2><p class="lede">${esc(Dd.league.name)}. Win 3, draw 1. The last three columns come from ${thousands(4000)} simulated runs of every remaining match to gameweek ${dEnd()}.</p>${help("Squad strength is the average expected score of each manager's best eleven across the remaining gameweeks. It is the fairest single measure of who has the better roster.")}
      <div class="panel d scroll"><table><thead><tr><th class="n">#</th><th>Team</th><th class="n">W-D-L</th><th class="n">Pts</th><th class="n">Scored</th><th class="n">Squad strength</th><th class="n">Finish first</th><th class="n">Top three</th></tr></thead><tbody>${tbl}</tbody></table>
      ${meR ? (() => { const mine = Dd.standings.find((x) => x.name === Dd.me) || {}, lead = Dd.standings[0] || {}, gap = (lead.pts || 0) - (mine.pts || 0), left = Dd.matches.filter((m) => !m.fin && m.gw <= dEnd() && (m.a === Dd.me || m.b === Dd.me)).length, played = (mine.w || 0) + (mine.d || 0) + (mine.l || 0);
        return `<p class="small muted">You are projected to finish around ${f1(meR.pos)} on ${f1(meR.pts)} league points. ${gap} points off the lead after ${played} rounds, with ${left} matches left to gameweek ${dEnd()}: mathematically alive, and your squad strength (${f1(meR.strength)}, ${ordinal(rc.slice().sort((a, b) => b.strength - a.strength).findIndex((r) => r.name === Dd.me) + 1)} best in the league) says the roster is not the whole problem. Selection and the waiver wire are.</p>`; })() : ""}</div></section>
    <section><h3>Your remaining Draft matches</h3><div class="panel scroll"><table><thead><tr><th>Gameweek</th><th>Opponent</th><th class="n">Their squad strength</th></tr></thead><tbody>${myFx}</tbody></table></div></section>
    <section><h2>Classic leagues</h2><p class="lede">Overall rank ${thousands(C.rank)} of ${thousands(C.players)}. The line shows your overall rank after each gameweek; up is better.</p><div class="panel c" style="color:var(--classic)">${sparkline(ranks, true)}<div class="legend" style="color:var(--ink2)">${C.season.map((s) => `<span>GW${s.gw}: ${thousands(s.rank)}</span>`).join("")}</div></div>
      ${help("Points a week to catch the leader is the gap divided by the gameweeks left. Beating a mini-league leader by three or four points every week for months is hard; one or two is realistic.")}
      <div class="panel scroll" style="margin-top:12px"><table><thead><tr><th>Mini-league</th><th class="n">Place</th><th class="n">This week</th><th class="n">Behind leader</th><th class="n">A week to gameweek ${cEnd}</th><th class="n">A week to gameweek 38</th><th class="n">To next place</th></tr></thead><tbody>${lg}</tbody></table></div></section>`;
  }

  /* ════════════ FIXTURES ════════════ */
  function vFixtures() { const g1 = Math.min(38, next + state.tickSpan - 1), T = M.ticker(next, g1), att = state.tickMode === "att", sorted = T.slice().sort((a, b) => att ? b.att - a.att : b.cs - a.cs);
    const cls = (c) => att ? (c.lf >= 1.95 ? "e1" : c.lf >= 1.6 ? "e2" : c.lf >= 1.25 ? "e3" : c.lf >= 1.0 ? "e4" : "e5") : (c.cs >= 0.42 ? "e1" : c.cs >= 0.33 ? "e2" : c.cs >= 0.25 ? "e3" : c.cs >= 0.18 ? "e4" : "e5");
    const head = []; for (let g = next; g <= g1; g++) head.push(`<th style="text-align:center">${g}</th>`);
    return `<section><h2>Fixture runs</h2><p class="lede">Every team's next ${state.tickSpan} matches, best run at the top. Green is good for the team in the row.</p>${help("Attack view shows the goals a team is expected to score in each match; pick attackers from green rows. Defence view shows the chance of a clean sheet; pick defenders and goalkeepers from green rows.")}
      <div class="row"><div class="seg"><button data-act="tmode" data-v="att" aria-pressed="${att}">Attack</button><button data-act="tmode" data-v="def" aria-pressed="${!att}">Defence</button></div><div class="seg">${[4, 6, 8, 14].map((n) => `<button data-act="tspan" data-v="${n}" aria-pressed="${state.tickSpan === n}">${n} weeks</button>`).join("")}</div></div>
      <div class="panel scroll"><table class="tick"><thead><tr><th>Team</th><th class="n">${att ? "Goals a match" : "Clean sheet"}</th>${head.join("")}</tr></thead><tbody>${sorted.map((t) => `<tr><td class="tm">${club(t.t)}${t.t}</td><td class="n num" style="text-align:right"><b>${att ? t.att.toFixed(2) : pct(t.cs)}</b></td>${t.row.map((cells) => `<td>${cells.length ? cells.map((c) => `<span class="cell ${cls(c)}">${c.o} ${c.ha}<br>${att ? c.lf.toFixed(1) : pct(c.cs)}</span>`).join("") : '<span class="cell e3">–</span>'}</td>`).join("")}</tr>`).join("")}</tbody></table></div></section>`; }

  /* ════════════ PLAYERS ════════════ */
  function vPlayers() { const q = state.q.trim().toLowerCase(); let L = DATA.players.filter((p) => p.st !== "u" && (!state.fpos || p.p === state.fpos) && (!state.ffree || (p.did && !p.do && p.ds === "a")) && (!q || (p.n + " " + p.fn + " " + p.t).toLowerCase().includes(q)));
    const key = { epn: (p) => M.ep(p, next), hor: (p) => M.epRange(p, next, cEnd), pts: (p) => p.pts, pr: (p) => p.pr, own: (p) => p.own, val: (p) => M.epRange(p, next, cEnd) / p.pr }[state.fsort] || ((p) => M.ep(p, next));
    L = L.map((p) => ({ p, k: key(p) })).sort((a, b) => b.k - a.k); const shown = L.slice(0, state.fmax);
    const th = (id, label) => `<th class="n"><button class="helpbtn" style="border:0;background:none;padding:0;font-weight:${state.fsort === id ? 700 : 600};text-decoration:${state.fsort === id ? "underline" : "none"}" data-act="fsort" data-v="${id}">${label}</button></th>`;
    return `<section><h2>Every player</h2><p class="lede">${L.length} players match. Tap a column heading to sort by it.</p>
      <div class="row"><input type="text" placeholder="Search a name or club" value="${esc(state.q)}" data-input="q" aria-label="Search players" style="flex:1 1 180px"><div class="seg">${[[0, "All"], [1, "GKP"], [2, "DEF"], [3, "MID"], [4, "FWD"]].map((x) => `<button data-act="fpos" data-v="${x[0]}" aria-pressed="${state.fpos === x[0]}">${x[1]}</button>`).join("")}</div><button class="helpbtn" data-act="ffree" aria-pressed="${state.ffree}">Free in my Draft league</button></div>
      <div class="panel scroll"><table><thead><tr><th>Player</th><th>Pos</th>${th("pr", "Price")}${th("pts", "Points")}${th("epn", "Gameweek " + next)}${th("hor", "To gameweek " + cEnd)}${th("val", "Per £m")}${th("own", "Owned")}<th>Draft owner</th></tr></thead><tbody>${shown.map((x) => { const p = x.p; return `<tr><td>${club(p.t)}${flag(p)}${esc(p.n)} <span class="muted small">${p.t}</span></td><td>${M.POS[p.p]}</td><td class="n">${money(p.pr)}</td><td class="n">${p.pts}</td><td class="n">${f1(M.ep(p, next))}</td><td class="n"><b>${f0(M.epRange(p, next, cEnd))}</b></td><td class="n">${f1(M.epRange(p, next, cEnd) / p.pr)}</td><td class="n">${f1(p.own)}%</td><td class="small">${p.do ? esc(p.do) : p.ds === "l" ? "on waivers" : p.did ? '<span class="good">free</span>' : "–"}</td></tr>`; }).join("")}</tbody></table></div>
      ${L.length > state.fmax ? `<div class="row"><button class="btn ghost" data-act="more">Show 40 more</button></div>` : ""}</section>`; }

  /* ════════════ ODDS ════════════ */
  function devig(h, d, a) { const ih = 1 / h, id = 1 / d, ia = 1 / a, s = ih + id + ia; return { h: ih / s, d: id / s, a: ia / s, margin: s - 1 }; }
  function fitRates(t) { let best = null; for (let lh = 0.3; lh <= 3.6; lh += 0.05) for (let la = 0.3; la <= 3.6; la += 0.05) { const o = M.matchOdds(lh, la), e = Math.pow(o.h - t.h, 2) + Math.pow(o.d - t.d, 2) + Math.pow(o.a - t.a, 2); if (!best || e < best.e) best = { lh, la, e }; } return best; }
  function vOdds() { const gws = [focus].concat(focus !== next ? [next] : [next + 1].filter((g) => g <= 38)), blocks = gws.map((gw) => { const rows = DATA.fixtures.filter((f) => f.gw === gw).sort((a, b) => (a.ko || "").localeCompare(b.ko || "")).map((f) => { const L = M.lambdas(f.h, { o: f.a, ha: "H" }, gw), o = M.matchOdds(L.lf, L.la);
        return `<tr><td>${club(f.h)}${f.h} v ${club(f.a)}${f.a}<br><span class="muted small">${sast(f.ko)}</span></td><td class="n">${L.lf.toFixed(2)} – ${L.la.toFixed(2)}</td><td class="n">${pct(o.h)} / ${pct(o.d)} / ${pct(o.a)}</td><td class="n">${pct(Math.exp(-L.la))} / ${pct(Math.exp(-L.lf))}</td><td class="small">${L.src === "odds" ? "bookmaker match prices" : L.src === "market" ? "bookmaker goal and clean-sheet prices" : "model"}</td></tr>`; }).join("");
      return `<h3>Gameweek ${gw}</h3><div class="panel scroll"><table><thead><tr><th>Match</th><th class="n">Expected goals</th><th class="n">Home / draw / away</th><th class="n">Clean sheet home / away</th><th>Source</th></tr></thead><tbody>${rows}</tbody></table></div>`; }).join("");
    const fxs = DATA.fixtures.filter((f) => f.gw === next || f.gw === focus), sel = fxs.find((f) => String(f.id) === String(state.oddsFx)) || fxs.find((f) => f.gw === next) || fxs[0];
    const h = parseFloat(state.oH), d = parseFloat(state.oD), a = parseFloat(state.oA), ok = h > 1 && d > 1 && a > 1; let calc = `<p class="muted small">Type the three decimal prices from any bookmaker, for example 1.45, 4.60 and 7.00.</p>`;
    if (ok) { const fair = devig(h, d, a), fit = fitRates(fair); calc = `<div class="note">Bookmaker margin removed: ${(fair.margin * 100).toFixed(1)}%. Fair chances: home ${pct(fair.h)}, draw ${pct(fair.d)}, away ${pct(fair.a)}. That implies ${sel.h} ${fit.lh.toFixed(2)} goals, ${sel.a} ${fit.la.toFixed(2)} goals, clean sheets ${pct(Math.exp(-fit.la))} and ${pct(Math.exp(-fit.lh))}.</div><div class="row"><button class="btn" data-act="applyodds">Use these numbers for ${sel.h} v ${sel.a}</button></div>`; }
    const ov = []; Object.keys(state.market || {}).forEach((g) => Object.keys(state.market[g]).forEach((t) => ov.push(`<li>Gameweek ${g}, ${t}: ${state.market[g][t].xg.toFixed(2)} goals <button class="helpbtn" data-act="rmodds" data-g="${g}" data-t="${t}">Remove</button></li>`)));
    return `<section><h2>Match odds</h2><p class="lede">Where a bookmaker price is loaded the app trusts it over its own rating. Everything else comes from the team ratings.</p>${help("Bookmakers build a profit margin into every price. Removing it gives the market's honest view of each result, and from that the goals each side is expected to score. Those goals drive every player projection in the app.")}${blocks}</section>
    <section><h3>Add a bookmaker price</h3><div class="panel"><div class="row"><select data-input="oddsFx" aria-label="Match">${fxs.map((f) => `<option value="${f.id}" ${sel && f.id === sel.id ? "selected" : ""}>GW${f.gw} ${f.h} v ${f.a}</option>`).join("")}</select></div>
      <div class="row"><label class="small">Home <input type="number" step="0.01" min="1" inputmode="decimal" value="${esc(state.oH)}" data-input="oH"></label><label class="small">Draw <input type="number" step="0.01" min="1" inputmode="decimal" value="${esc(state.oD)}" data-input="oD"></label><label class="small">Away <input type="number" step="0.01" min="1" inputmode="decimal" value="${esc(state.oA)}" data-input="oA"></label><button class="btn ghost" data-act="calc">Work it out</button></div>${calc}
      ${ov.length ? `<h3 style="margin-top:12px">Prices you have added</h3><ul class="plain">${ov.join("")}</ul>` : ""}</div></section>`; }

  /* ════════════ REVIEW ════════════ */
  function vReview() { const c = M.classicReview(5), d = M.draftReview(5);
    const cBench = c.reduce((s, g) => s + g.leftOnBench, 0), cCap = c.reduce((s, g) => s + g.capGap, 0), cVsAvg = c.reduce((s, g) => s + (g.pts - g.avg), 0), capHits = c.filter((g) => g.capGap === 0).length;
    const dBench = d.reduce((s, g) => s + g.leftOnBench, 0), flips = d.filter((g) => g.flip), dW = d.filter((g) => g.res === "W").length;
    const cRepeat = [], cStop = [], dRepeat = [], dStop = [];
    if (cVsAvg > 0) cRepeat.push(`You beat the average by ${f0(cVsAvg)} points across ${c.length} gameweeks. The core of the squad is sound.`); else cStop.push(`You trail the average by ${f0(-cVsAvg)} points across ${c.length} gameweeks.`);
    if (capHits >= Math.ceil(c.length / 2)) cRepeat.push(`Captaincy was the best available in ${capHits} of ${c.length} gameweeks. Keep following the expected-points leader.`); if (cCap > 6) cStop.push(`Captain choices cost ${f0(cCap)} points against the best option in your own squad. Use the armband table, not instinct.`);
    const cRaw = c.reduce((s, g) => s + (g.bench || 0), 0);
    if (cBench > 8) cStop.push(`Your bench scored ${f0(cRaw)} points across ${c.length} gameweeks, and ${f0(cBench)} of those were points a better eleven would have had on the pitch. Set the team from the best-eleven view every week, and re-check it after Friday's press conferences.`); else cRepeat.push(`Team selection was tight: your bench scored ${f0(cRaw)}, of which only ${f0(cBench)} was avoidable.`);
    if (c.every((g) => !g.tx)) cStop.push(`No transfers made in ${c.length} gameweeks. Banking is fine up to five, but ${classicState ? classicState.ft : "several"} unused transfers means upgrades you could have had weeks ago are still waiting.`);
    if (dW === 0 && d.length) dStop.push(`No wins in ${d.length}. Points scored (${(DATA.draft.standings.find((s) => s.name === DATA.draft.me) || {}).pf}) sits in the bottom two of the league, so this is a roster problem, not bad luck alone.`);
    if (flips.length) dStop.push(`${flips.length} result${flips.length > 1 ? "s" : ""} (gameweek ${flips.map((g) => g.gw).join(", ")}) would have flipped with your best eleven on the pitch. Set the Draft eleven from this app's best-eleven view.`);
    if (dBench > 10) dStop.push(`${f0(dBench)} points sat on the Draft bench that the best eleven would have played, across ${d.length} gameweeks. In a head-to-head league decided by two points twice already, that is the whole season.`); else if (d.length) dRepeat.push(`Draft selection was efficient: ${f0(dBench)} points left on the bench in ${d.length} gameweeks.`);
    dRepeat.push(`Work the free-agent list every week. With a re-draft coming, a player's value after the horizon is zero, so always hold the fifteen who score most between now and then.`);
    const cRows = c.map((g) => `<tr><td>${g.gw}</td><td class="n">${g.pts}</td><td class="n">${g.avg}</td><td class="n">${thousands(g.rank)}</td><td>${g.cap ? esc(g.cap.n) + " " + g.cap.pts : "–"}</td><td>${g.capGap > 0 && g.bestCap ? esc(g.bestCap.n) + " " + g.bestCap.pts : "best pick"}</td><td class="n">${g.bench}</td><td class="n">${f0(g.leftOnBench)}</td><td class="small">${g.top.map((t) => esc(t.n) + " " + t.pts).join(", ")}</td></tr>`).join("");
    const dRows = d.map((g) => `<tr><td>${g.gw}</td><td>${g.res === "W" ? '<span class="good">Won</span>' : g.res === "L" ? '<span class="bad">Lost</span>' : g.res === "D" ? "Drew" : "–"}</td><td class="n">${g.mine != null ? g.mine + "–" + g.opp : "–"}</td><td>${esc(g.oppName || "")}</td><td class="n">${f0(g.leftOnBench)}</td><td>${g.flip ? '<span class="bad">yes</span>' : "no"}</td><td class="small">${g.top.map((t) => esc(t.n) + " " + t.pts).join(", ")}</td></tr>`).join("");
    const led = (DATA.classic.transfersLog || []).map((t) => { const hi = (P[t.in] && P[t.in].h) || {}, ho = (P[t.out] && P[t.out].h) || {}; let pi = 0, po = 0; for (let g = t.gw; g <= G.lastDone; g++) { pi += hi[g] ? hi[g][1] : 0; po += ho[g] ? ho[g][1] : 0; } return { t, pi, po }; });
    led.forEach((x) => { const t = x.t; (x.pi >= x.po ? cRepeat : cStop).push(`Gameweek ${t.gw}: ${esc(P[t.out] ? P[t.out].n : "?")} (sold ${money(t.outCost)}) to ${esc(P[t.in] ? P[t.in].n : "?")} (bought ${money(t.inCost)}). Since then ${x.pi} points against ${x.po}, ${sign(x.pi - x.po)}.`); });
    if (led.length && !c.every((g) => !g.tx)) { const unused = classicState ? classicState.ft : 0; if (unused >= 4) cStop.push(`${unused} free transfers are banked for gameweek ${next}. Five is the most you can hold, so ${unused >= 5 ? "rolling this week throws one away" : "rolling this week and next throws one away"}. A wildcard week keeps the bank exactly as it is.`); }
    const list = (t, a) => a.length ? `<h3>${t}</h3><ul class="plain">${a.map((x) => `<li>${x}</li>`).join("")}</ul>` : "";
    return `<section><h2>Review of the last ${Math.max(c.length, d.length)} gameweeks</h2><p class="lede">What to repeat and what to stop, each game on its own. It rebuilds itself after every gameweek and always looks at the most recent five. "Avoidable" means points that were in your squad and on the bench when a better legal eleven was available.</p></section>
    <section><span class="tag c">Classic</span><div class="panel c" style="margin-top:8px">${list("Repeat", cRepeat)}${list("Stop", cStop)}</div><div class="panel scroll" style="margin-top:10px"><table><thead><tr><th>GW</th><th class="n">You</th><th class="n">Average</th><th class="n">Overall rank</th><th>Captain</th><th>Better captain in squad</th><th class="n">Bench scored</th><th class="n">Avoidable</th><th>Top scorers</th></tr></thead><tbody>${cRows}</tbody></table></div></section>
    <section><span class="tag d">Draft</span><div class="panel d" style="margin-top:8px">${list("Repeat", dRepeat)}${list("Stop", dStop)}</div><div class="panel scroll" style="margin-top:10px"><table><thead><tr><th>GW</th><th>Result</th><th class="n">Score</th><th>Opponent</th><th class="n">Avoidable bench points</th><th>Best eleven would have changed it</th><th>Top scorers</th></tr></thead><tbody>${dRows}</tbody></table></div></section>`; }

  /* ════════════ LAB ════════════ */
  function vLab() { const t = R.tests || PRE.tests || null, cal = M.calib, fair = (DATA.intel.sources || []).map((s) => `<li>${esc(s)}</li>`).join("");
    return `<section><h2>How the numbers are made</h2><p class="lede">Plain account of the model, its checks and its limits.</p>
      <div class="panel"><ul class="plain"><li><b>Team strength.</b> Each side's attack and defence start from what the game's own prices imply, then move toward this season's opponent-adjusted expected goals (70%) and goals (30%). After ${G.lastDone} gameweeks the season carries about a third of the weight.</li>
      <li><b>Market check.</b> The price-to-strength scale is fitted so the model reproduces ${cal.n} bookmaker-implied numbers from gameweeks ${(cal.weeks || [5]).join(", ")}; match prices are turned into goals for each side by removing the margin and fitting the scoreline odds. Typical miss: ${cal.rmse != null ? (cal.rmse * 100).toFixed(0) + "%" : "–"} per number. Where a market number exists, it is used instead of the model.</li>
      <li><b>Players.</b> Expected goals and assists per 90 minutes this season, pulled toward a price-based prior worth six matches, scaled by the fixture. Clean sheets, goals conceded, saves, bonus, defensive contributions (10 actions for defenders, 12 for others, 2 points, once a match) and cards are all priced in.</li>
      <li><b>Backtest and correction.</b> Every build re-forecasts the last three gameweeks from what was known at the time and scores the forecasts; position corrections come only from that evidence. See the backtest table below.</li>
      <li><b>Minutes.</b> Recent starts count double. Official flags set availability; return dates switch players back on in the right gameweek. Where reporting runs ahead of an official flag, a dated override is used and shown next to the player.</li>
      <li><b>Optimisation.</b> The Classic plan is a mixed-integer programme over every gameweek to 19: squad, eleven, captain, transfers, hits, the free-transfer bank and the chip weeks are decided together, solved exactly to a stated tolerance. The Draft roster is solved the same way to the re-draft. The quick searches on the Classic and Draft tabs are greedy, run on your phone, and exist for what-if checks.</li>
      <li><b>Simulation.</b> Each run draws every scoreline, then deals goals and assists to players by their share, so team-mates rise and fall together. Substitutes come on automatically in bench order, as in the real game.</li></ul></div></section>
    ${backtestHtml()}
    <section><h3>Self-test</h3><div class="panel">${t ? `<p><b>${t.pass} of ${t.total}</b> checks pass${t.at ? ", run " + sast(t.at) + " SAST" : ""}.</p>${t.fails && t.fails.length ? `<ul class="plain">${t.fails.map((x) => `<li class="bad">${esc(x)}</li>`).join("")}</ul>` : ""}` : `<p class="muted">Not run in this session yet.</p>`}<div class="row"><button class="btn" data-act="run" data-v="tests" ${state.busy ? "disabled" : ""}>${state.busy === "tests" ? "Running…" : "Run the checks on this device"}</button></div>
      <p class="small muted">The checks cover the maths (probabilities sum to one, expected points never negative), the rules (every eleven legal, three a club, budget respected), the two games staying separate, and every tab rendering.</p></div></section>
    <section><h3>What it cannot see</h3><div class="panel"><ul class="plain"><li>This page cannot fetch live data by itself. Numbers refresh when the app is rebuilt from the feeds; ask for an update in chat.</li><li>Your saved Classic team for the next gameweek is private until the deadline passes. The app plans from your last published team, which is also your current fifteen unless you have made transfers since.</li><li>Rivals' Draft elevens publish only after each deadline. Before that the app assumes their best eleven.</li><li>A sample of ${G.lastDone} played gameweek${G.lastDone === 1 ? "" : "s"} is small. Early-season projections lean on prices and will sharpen each week.</li><li>Bookmaker prices are loaded for ${oddsCover()}. Beyond that the team ratings carry the fixtures; add prices on the Odds tab as they appear.</li></ul></div></section>
    <section><h3>Sources</h3><div class="panel"><ul class="plain"><li>Official Fantasy Premier League and FPL Draft public feeds, pulled ${sast(DATA.asOf)} SAST</li>${fair}</ul></div></section>`; }

  function oddsCover() { const O = DATA.intel.odds || {}, gs = Object.keys(O).map(Number).filter((g) => g >= next && (O[g] || O[String(g)] || []).length).sort((a, b) => a - b);
    if (!gs.length) return "no gameweek yet";
    return gs.map((g) => { const have = (O[g] || O[String(g)] || []).length, all = DATA.fixtures.filter((f) => f.gw === g).length; return `gameweek ${g} (${have} of ${all} matches)`; }).join(gs.length > 2 ? ", " : " and "); }

  function backtestHtml() { const m = DATA.model; if (!m || !m.backtest) return ""; const b = m.backtest, pos = b.points.byPos, nm = { 1: "Goalkeepers", 2: "Defenders", 3: "Midfielders", 4: "Forwards" };
    const rows = Object.keys(pos).map((k) => { const x = pos[k]; return `<tr><td>${nm[k]}</td><td class="n">${x.n}</td><td class="n">${f1(x.meanPred)}</td><td class="n">${f1(x.meanAct)}</td><td class="n">${x.ratio.toFixed(2)} <span class="muted small">(${x.lo.toFixed(2)}–${x.hi.toFixed(2)})</span></td><td class="n">${x.rho.toFixed(2)} / ${x.rhoNaive.toFixed(2)}</td><td class="n">${f1(x.mae)} / ${f1(x.maeNaive)}</td><td class="n"><b>${(m.calib[k] || 1).toFixed(3)}</b></td></tr>`; }).join("");
    return `<section><h3>Walk-forward backtest, gameweeks ${b.weeks.join(", ")}</h3>${help("Each gameweek is forecast again using only what was known before its deadline, then scored against what happened. Points are judged only for players who started, so injuries the model could not see do not distort the result; who starts is judged separately.")}
      <div class="panel scroll"><table><thead><tr><th>Points given a start</th><th class="n">Starts</th><th class="n">Forecast</th><th class="n">Actual</th><th class="n">Actual ÷ forecast (90% range)</th><th class="n">Rank corr. model / naive</th><th class="n">Error model / naive</th><th class="n">Correction applied</th></tr></thead><tbody>${rows}</tbody></table>
      <p class="small">Who starts: Brier score ${b.minutes.brier.toFixed(3)} against ${b.minutes.brierNaive.toFixed(3)} for "same as last week" (lower is better), over ${b.minutes.n} player-weeks; forecast start chances land within ${Math.round(100 * Math.max.apply(null, b.minutes.buckets.filter((x) => x.n >= 30).map((x) => Math.abs(x.pred - x.act))))} points of the observed rate in every band. Team goals: log-likelihood ${b.goals.logLik.toFixed(1)} against ${b.goals.logLikNaive.toFixed(1)} for a flat league average over ${b.goals.n} matches, no better yet on this small sample.</p>
      <p class="small muted">A correction is applied only where the 90% range excludes 1, at half the observed gap and never more than 15%. The naive benchmark is each player's points per start so far.</p></div></section>`; }
  function selfTest() { const fails = []; let total = 0; const ok = (c, m) => { total++; if (!c) fails.push(m); };
    const o = M.matchOdds(1.6, 1.1); ok(Math.abs(o.h + o.d + o.a - 1) < 1e-9, "match odds sum to one"); ok(M.maths.poisTail(0, 2) === 1, "Poisson tail at zero");
    DATA.players.slice(0, 200).forEach((p) => { const e = M.ep(p, next); ok(isFinite(e) && e > -1.5 && e < 20, "expected points in range for " + p.n); });
    if (classicState) { const b = M.bestXI(classicState.squad, next); ok(b && b.xi.length === 11, "Classic eleven has 11"); ok(b && b.xi.filter((p) => p.p === 1).length === 1, "one goalkeeper"); const c = {}; classicState.squad.forEach((p) => { c[p.t] = (c[p.t] || 0) + 1; }); ok(Object.values(c).every((n) => n <= 3), "three a club in your squad"); }
    const b2 = M.bestXI(myRoster, next); ok(b2 && b2.xi.length === 11, "Draft eleven has 11"); ok(myRoster.length === 15, "Draft roster has 15"); ok(M.freeAgents().every((p) => !p.do), "free agents are unowned");
    TABS.forEach((t) => { try { const h = view(t[0]); ok(typeof h === "string" && h.length > 200, "tab renders: " + t[1]); } catch (e) { ok(false, "tab crashed: " + t[1] + " (" + e.message + ")"); } });
    return { pass: total - fails.length, total, fails, at: new Date().toISOString() }; }

  /* ── frame ── */
  function view(tab) { return ({ today: vToday, classic: vClassic, draft: vDraft, leagues: vLeagues, fixtures: vFixtures, players: vPlayers, odds: vOdds, review: vReview, lab: vLab }[tab] || vToday)(); }
  function render() { return `<div class="wrap ${state.explain ? "explain" : ""}"><header class="mast"><div><h1>Mission Control</h1><div class="muted small">Fantasy Premier League, two games kept apart. ${VERSION}</div></div><div class="stamp"><button class="helpbtn" data-act="explain" aria-pressed="${state.explain}">${state.explain ? "Hide explanations" : "Explain everything"}</button><br>data ${sast(DATA.asOf)} SAST</div></header>
    <nav class="tabs" role="tablist" aria-label="Sections">${TABS.map((t) => `<button class="tab ${t[2]}" role="tab" aria-selected="${state.tab === t[0]}" data-act="tab" data-v="${t[0]}">${t[1]}</button>`).join("")}</nav><main>${view(state.tab)}</main>
    <footer class="foot">Expected points are averages, not promises. Classic and Draft are separate games and are never added together here.</footer></div>`; }

  const HEAVY = { tr: () => { const r = M.classicTransfers(classicState, next, cEnd, Math.min(classicState.ft, 5)); R.tr = { moves: r.moves.map((m) => ({ out: m.out.id, inn: m.inn.id, gain: m.gain, gainNext: m.gainNext, bankAfter: m.bankAfter })), value: r.value }; },
    wc: () => { const budget = classicState.squad.reduce((s, p) => s + p.sell, 0) + classicState.bank, w = M.wildcard(budget, next, cEnd, { perPos: 26 }); if (w) R.wc = { squad: w.squad.map((p) => p.id), cost: w.cost, budget: w.budget, value: w.value }; if (!transfers()) HEAVY.tr(); },
    trade: () => { R.trades = findTrades(); }, tests: () => { R.tests = selfTest(); } };
  function act(name, el, rerender, later) { const v = el && el.getAttribute ? el.getAttribute("data-v") : null; let top = false;
    if (name === "tick") { state.done = state.done || {}; state.done[v] = !state.done[v]; }
    else if (name === "tab") { state.tab = v; top = true; } else if (name === "explain") state.explain = !state.explain; else if (name === "xi") state.xiMode = v; else if (name === "fapos") state.faPos = +v; else if (name === "fpos") { state.fpos = +v; state.fmax = 40; } else if (name === "ffree") { state.ffree = !state.ffree; state.fmax = 40; }
    else if (name === "fsort") state.fsort = v; else if (name === "more") state.fmax += 40; else if (name === "tmode") state.tickMode = v; else if (name === "tspan") state.tickSpan = +v; else if (name === "calc") { /* values already in state */ }
    else if (name === "dend") { state.draftEnd = +v; M.setDraftEnd(state.draftEnd); ["mv", "duel", "race", "trades"].forEach((k) => { delete R[k]; }); }
    else if (name === "applyodds") { const fxs = DATA.fixtures, sel = fxs.find((f) => String(f.id) === String(state.oddsFx)) || fxs.find((f) => f.gw === next), h = parseFloat(state.oH), d = parseFloat(state.oD), a = parseFloat(state.oA); if (sel && h > 1 && d > 1 && a > 1) { const fit = fitRates(devig(h, d, a)); state.market = state.market || {}; state.market[sel.gw] = Object.assign({}, state.market[sel.gw] || {}); state.market[sel.gw][sel.h] = { xg: fit.lh }; state.market[sel.gw][sel.a] = { xg: fit.la }; M.setMarket(state.market); Object.keys(R).forEach((k) => { if (k !== "tests") delete R[k]; }); } }
    else if (name === "rmodds") { const g = el.getAttribute("data-g"), t = el.getAttribute("data-t"); if (state.market[g]) { delete state.market[g][t]; if (!Object.keys(state.market[g]).length) delete state.market[g]; } M.setMarket(state.market); Object.keys(R).forEach((k) => { if (k !== "tests") delete R[k]; }); }
    else if (name === "run" && HEAVY[v]) { state.busy = v; rerender(false); (later || ((fn) => fn()))(() => { try { HEAVY[v](); } catch (e) { R.err = e.message; } state.busy = null; rerender(false); if (store) store.save(persisted()); }); return; }
    if (store) store.save(persisted()); rerender(top); }
  function input(key, value) { if (["q", "oH", "oD", "oA", "oddsFx"].includes(key)) { state[key] = value; if (key === "q") state.fmax = 40; if (store) store.save(persisted()); } }
  const persisted = () => ({ tab: state.tab, explain: state.explain, draftEnd: state.draftEnd, market: state.market, tickMode: state.tickMode, tickSpan: state.tickSpan, done: state.done });
  return { state, render, view, act, input, selfTest, findTrades, buildClaimSheet, TABS, VERSION, helpers: { sast, countdown, devig, fitRates } };
}

function boot(M, DATA, PRE) {
  const KEY = "mission-control-v1"; const store = { load: () => { try { return JSON.parse(localStorage.getItem(KEY) || "null"); } catch (e) { return null; } }, save: (s) => { try { localStorage.setItem(KEY, JSON.stringify(s)); } catch (e) { /* storage can be unavailable; the app works without it */ } } };
  const ui = makeUI(M, DATA, PRE, store), rootEl = document.getElementById("app");
  function paint(toTop) { const active = document.activeElement, id = active && active.getAttribute ? active.getAttribute("data-input") : null, pos = id && active.selectionStart != null ? active.selectionStart : null;
    rootEl.innerHTML = ui.render(); if (toTop) { window.scrollTo(0, 0); const tabs = rootEl.querySelector(".tab[aria-selected='true']"); if (tabs && tabs.scrollIntoView) tabs.scrollIntoView({ block: "nearest", inline: "center" }); }
    if (id) { const el = rootEl.querySelector('[data-input="' + id + '"]'); if (el) { el.focus(); try { if (pos != null) el.setSelectionRange(pos, pos); } catch (e) { /* number inputs have no selection */ } } } tick(); }
  function tick() { rootEl.querySelectorAll("[data-countdown]").forEach((el) => { const t = new Date(el.getAttribute("data-countdown")).getTime(); if (t) el.textContent = ui.helpers.countdown(t - Date.now()); }); }
  document.addEventListener("click", (e) => { const el = e.target.closest ? e.target.closest("[data-act]") : null; if (!el || el.disabled) return; ui.act(el.getAttribute("data-act"), el, paint, (fn) => setTimeout(fn, 30)); });
  document.addEventListener("input", (e) => { const el = e.target; const k = el.getAttribute && el.getAttribute("data-input"); if (!k) return; ui.input(k, el.value); if (k === "q") paint(false); });
  document.addEventListener("change", (e) => { const el = e.target; const k = el.getAttribute && el.getAttribute("data-input"); if (k === "oddsFx") { ui.input(k, el.value); paint(false); } });
  paint(true); setInterval(tick, 30000); return ui;
}
return { makeUI, boot, VERSION };
});
