#!/usr/bin/env node
/* build.cjs — assembles the single file and the standalone page (CONTRACT §2).
 *
 *   app/FPL_Mission_Control.jsx  imports · APP_VERSION · engine · weekly · live · ui
 *   dist/index.html              esbuild IIFE bundle of that file, inlined, with a
 *                                window.storage shim over localStorage.
 *
 * Marker text is exact and each marker appears once, in order; verify.sh asserts it.
 */
"use strict";

const fs = require("fs");
const path = require("path");
const esbuild = require("esbuild");

const ROOT = __dirname;
const P = function (...parts) { return path.join(ROOT, ...parts); };
const read = function (rel) { return fs.readFileSync(P(rel), "utf8"); };

const pkg = JSON.parse(read("package.json"));
const APP_VERSION = "v" + String(pkg.version).split(".")[0];

const M = {
  engineStart: "// ENGINE — START",
  engineEnd: "// ENGINE — END",
  weeklyStart: "// WEEKLY STRATEGY ENGINE — START",
  weeklyEnd: "// WEEKLY STRATEGY ENGINE — END",
  liveStart: "// LIVE DATA — START",
  liveEnd: "// LIVE DATA — END"
};

/* The import lines have to stay at the top of an ES module, so they are lifted off
   src/ui.jsx and everything else follows the data blocks. Collection stops at the first
   statement that is not an import, which is why an import written further down the file
   would be dropped silently: the body is scanned afterwards and a late import throws with
   its line number instead. (The old code also tested for an import inside the branch that
   had already established the line was blank or a comment, which could never be true.) */
function splitImports(src) {
  const lines = src.split("\n");
  const imports = [];
  let i = 0;
  for (; i < lines.length; i++) {
    const t = lines[i].trim();
    if (t === "" || t.startsWith("//")) continue;
    if (t.startsWith("import ")) { imports.push(lines[i]); continue; }
    break;
  }
  const rest = lines.slice(i);
  for (let k = 0; k < rest.length; k++) {
    if (rest[k].trim().startsWith("import ")) {
      throw new Error("src/ui.jsx line " + (i + k + 1) + " is an import after the first statement: " +
        rest[k].trim().slice(0, 80) + " — move it to the top of the file; the assembler would otherwise drop it");
    }
  }
  return { imports: imports, rest: rest.join("\n") };
}

function jsLiteral(obj) {
  return JSON.stringify(obj).replace(/\u2028/g, "\\u2028").replace(/\u2029/g, "\\u2029");
}

function assemble() {
  const ui = splitImports(read("src/ui.jsx"));
  const engine = read("src/engine.js").trim();
  const weekly = read("data/weekly.js").trim();
  const live = JSON.parse(read("data/live.json"));

  const out = [
    "/* FPL Mission Control " + APP_VERSION + " — assembled by build.cjs; edit src/ui.jsx, src/engine.js,",
    "   data/weekly.js or data/live.json and run `npm run build`. Do not edit this file. */",
    ui.imports.join("\n"),
    "",
    "const APP_VERSION = \"" + APP_VERSION + "\";",
    "",
    M.engineStart,
    engine,
    M.engineEnd,
    "",
    M.weeklyStart,
    weekly,
    M.weeklyEnd,
    "",
    M.liveStart,
    "const LIVE = " + jsLiteral(live) + ";",
    M.liveEnd,
    "",
    ui.rest.trim(),
    ""
  ].join("\n");

  const order = Object.keys(M).map(function (k) { return { key: k, text: M[k], at: out.indexOf(M[k]) }; });
  order.forEach(function (m) {
    const n = out.split(m.text).length - 1;
    if (n !== 1) throw new Error("marker " + m.text + " appears " + n + " times, expected 1");
  });
  for (let i = 1; i < order.length; i++) {
    if (order[i].at < order[i - 1].at) throw new Error("marker out of order: " + order[i].text);
  }
  /* The banned fields must not reach the data block or be read anywhere: the only
     permitted mention is the engine header comment that names them as banned. */
  const liveBlock = out.slice(out.indexOf(M.liveStart), out.indexOf(M.liveEnd));
  if (/ep_this|ep_next/.test(liveBlock)) throw new Error("banned field ep_this/ep_next is in the live data block");
  const reads = out.match(/\.ep_(this|next)\b|\[\s*["']ep_(this|next)/g);
  if (reads) throw new Error("banned field read in code: " + reads.join(", "));

  fs.mkdirSync(P("app"), { recursive: true });
  fs.writeFileSync(P("app/FPL_Mission_Control.jsx"), out);
  return out;
}

function bundle() {
  const entry = [
    "import React from \"react\";",
    "import { createRoot } from \"react-dom/client\";",
    "import App from \"./app/FPL_Mission_Control.jsx\";",
    "const el = document.getElementById(\"root\");",
    "createRoot(el).render(React.createElement(App));"
  ].join("\n");
  const res = esbuild.buildSync({
    stdin: { contents: entry, resolveDir: ROOT, sourcefile: "entry.jsx", loader: "jsx" },
    bundle: true,
    format: "iife",
    jsx: "automatic",
    loader: { ".jsx": "jsx" },
    minifySyntax: true,
    legalComments: "none",
    define: { "process.env.NODE_ENV": "\"production\"" },
    logLevel: "error",
    write: false
  });
  return res.outputFiles[0].text;
}

function page(js) {
  const shim = [
    "(function(){",
    "  if (window.storage && typeof window.storage.get === 'function') return;",
    "  window.storage = {",
    "    get: function(k){ try { var v = localStorage.getItem(k); return Promise.resolve(v === null ? null : { value: JSON.parse(v) }); } catch (e) { return Promise.resolve(null); } },",
    "    set: function(k, v){ try { localStorage.setItem(k, JSON.stringify(v)); } catch (e) {} return Promise.resolve(true); }",
    "  };",
    "})();"
  ].join("\n");
  return [
    "<!doctype html>",
    "<html lang=\"en-ZA\">",
    "<head>",
    "<meta charset=\"utf-8\">",
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, viewport-fit=cover\">",
    "<meta name=\"color-scheme\" content=\"dark\">",
    "<title>FPL Mission Control " + APP_VERSION + "</title>",
    /* CONTRACT §7 allows hex only inside the token definitions, which live in the app's own
       single <style> block. This shell block therefore carries no colour at all: it would be a
       second, unwatched copy of --bg and --text, free to drift from the tokens. The dark canvas
       before React mounts comes from the color-scheme meta above, and .mc-root paints var(--bg)
       over the full viewport the moment it renders. */
    "<style>html,body{margin:0;padding:0}#root{min-height:100vh}</style>",
    "</head>",
    "<body>",
    "<div id=\"root\"></div>",
    "<script>" + shim + "</script>",
    "<script>" + js.replace(/<\/script/gi, "<\\/script") + "</script>",
    "</body>",
    "</html>",
    ""
  ].join("\n");
}

function main() {
  const jsx = assemble();
  const js = bundle();
  fs.mkdirSync(P("dist"), { recursive: true });
  const html = page(js);
  fs.writeFileSync(P("dist/index.html"), html);
  const kb = function (s) { return (Buffer.byteLength(s, "utf8") / 1024).toFixed(0) + " kB"; };
  console.log("app/FPL_Mission_Control.jsx  " + kb(jsx));
  console.log("dist/index.html              " + kb(html));
  console.log("version " + APP_VERSION + "  markers 6/6  order ok");
}

main();
